### ISSUE TITLE
Adding Directives to Schemas

### ISSUE THREAD

**Issue by MDrooker** [graphql-compose/graphql-compose-mongoose#105]
Hey All-
We are looking to use the new ApolloServer 2.0 features around CDN integration for some of our services-

[https://www.apollographql.com/docs/apollo-server/v2/features/cdn.html](https://www.apollographql.com/docs/apollo-server/v2/features/cdn.html)

Any suggestions around how to get the directives added to some of the types output by graphql-compose-mongoose?

**Comment by stoffern** [comment]
Just wrap it with Dataloader and you have solved the issue:
https://github.com/graphql-compose/graphql-compose-dataloader

**Comment by MDrooker** [comment]
We want to put a CDN infront of our service to help scale it under load.  The Dataloader only helps with the calls to Mongo.  A CDN will cache the request/response so it serves from the edge vs the origin servers.

**Comment by stoffern** [comment]
That is not implemented in graphql-compose. 
I think it would be fairly simple and easy to make a middeware for it that attaches to the TCs.

In our environment, we use [serverless](https://serverless.com/) for automatic AWS deployment and run everything in lambda as it is autoscaling and you only pay pr runtime as it is really cheap

**Comment by marckline** [comment]
One can imagine other use cases. For example, the schema directive that brought me here is https://github.com/confuser/graphql-constraint-directive. Others might want to create custom schema directives for their own servers (e.g. via https://www.apollographql.com/docs/graphql-tools/schema-directives.html). But there doesn't seem to be any documented or undocumented way of adding these to types unless I'm missing it?

**Comment by nodkz** [comment]
Adding directives via `GraphQL*Type` classes was rejected by Lee Byron https://github.com/graphql/graphql-js/issues/1262

It will be good if you write about your needs and use cases in the 1262 issue. Right now there is no way to add directives via `GraphQL*Type` classes in `graphql-js`. That's why `graphql-compose` which works on top of its classes does not allow to provide directives for fields when you define types.

**Comment by marc-money** [comment]
Thanks. I understand, and after exploring the topic some more, it looks to me like @19majkel94 did a good job making the same case I might have in https://github.com/graphql/graphql-js/issues/1343

It also looks like a related topic was discussed at a WG meeting a few months back: https://github.com/graphql/graphql-wg/blob/master/notes/2018-02-01.md#exposing-schema-metadata. Maybe some progress will be made soon.
