### ISSUE TITLE
need to replace syntax for .count to .countDocuments due to update

### ISSUE THREAD

**Issue by cKhoff** [graphql-compose/graphql-compose-mongoose#108]

**Comment by nodkz** [comment]
Can you explain what exactly is your problem?
Do you dislike `count` name for resolver? 

Resolver name does not restrict you with field name in your schema. You may choose any name, which will be available in queries eg `userCountDocuments`:
```js
schemaComposer.Query.addFields({
  userCountDocuments: UserTC.getResolver('count'),
});
```

**Comment by cKhoff** [comment]
sure, with the new mongoose update i´d an error like: '(node:10776) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead'
here´s the ref: http://mongoosejs.com/docs/api.html#query_Query-count

**Comment by nodkz** [comment]
Gotcha! Thanks for reporting. Will be fixed in minutes.
