### ISSUE TITLE
How to query and populate 'ref' data on subdocuments?

### ISSUE THREAD

**Issue by woh-dev** [graphql-compose/graphql-compose-mongoose#112]
In my app I can create a "POST". Any "POST" can have a "REACTION" which I save directly to an array on the "POST" object. Each "REACTION" is associated with a "USER". 

I would like to be able return the "USER" username and other details with each "REACTION" when I make a mutation.

I'm pretty new to GraphQL and GraphQL-Compose-Mongoose and I can't figure out how to return the "REACTION" subdocuments pre-populated with data from the "USER" ref.

I initially tried using **.populate('reactions.user')** to accomplish this, which returned the data that I wanted, but as a string. I think this is due to conflict with TYPE of my 'reactions.user' (mongoose.Schema.Types.ObjectId). Also, this method always returns the user data, instead of allowing users to query for what they want.

Here's an example mutation that I'd like to be able to accomplish:

```
mutation {
  postAddReaction(userId: "5b469f53a9685083cc22df7c", postId: "5b4e901a10d3663d29624633", reaction:"thumbs_up") {
    reactions {
      user {
        first
        last
        _id
      }
      reaction
    } 
  }
}
```
When I run this currently, I get the error _"Field \"user\" must not have a selection since type \"MongoID\" has no subfields."_ I don't understand how to get around this since I need to specify a type for on the schema.

Here's my (simplified) schema for POST.JS
```
var mongoose = require('mongoose');
var Model = require('./model')

var Schema = new Model({
 text: {
   type: String,
   trim: true,
   required: true
 },
 reactions: [{
   user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
   reaction: { type: String, required: true },
 }, { timestamps: true }
   ],
 author: {
   type: mongoose.Schema.Types.ObjectId,
   ref: 'User',
   index: true
 },
});

Schema.index({author: 1});

module.exports = mongoose.model('Post', Schema);
```

Here's is the USER.JS schema: 
```
var mongoose = require('mongoose');
var Model = require('./model');

var Schema = new Model({
 first: {
   type: String,
   trim: true,
   index: true
 },
 last: {
   type: String,
   trim: true,
   index: true
 },
 email: {
   type: String,
   lowercase: true,
   trim: true,
   required: true,
   unique: true,
   index: true
 },
});

module.exports = mongoose.model('User', Schema);
```

And the GRAPHQL-COMPOSE-MONGOOSE magic:
```
var { Resolver } = require('graphql-compose');
var composeWithMongoose = require('graphql-compose-mongoose').composeWithMongoose
var schemaComposer = require('graphql-compose').schemaComposer

const User = require('../models/user')
const userOptions = {};
const UserTC = composeWithMongoose(User, userOptions);

schemaComposer.rootQuery().addFields({
 user: UserTC.getResolver('findOne'),
 user: UserTC.getResolver('findMany'),
});

const Post = require('../models/post')
const postOptions = {};
const PostTC = composeWithMongoose(Post, postOptions);

schemaComposer.rootQuery().addFields({
 post: PostTC.getResolver('findOne'),
});

schemaComposer.rootMutation().addFields({
 postCreate: PostTC.getResolver('createOne'),
 postAddReaction: new Resolver({
   name: 'addReaction',
   type: PostTC,
   args: {
     userId: 'ID!',
     postId: 'ID!',
     reaction: 'String!',
   },
   resolve: ({ source, args, context, info }) => {
     return Post.findOneAndUpdate({_id: args.postId, 'reactions.user': {$ne: args.userId}},
       {
         $push: {
           reactions: {
             user: { _id: args.userId },
             reaction: args.reaction
           }
         }
       }, {new: true}).populate('reactions.details'),
 }),
});

PostTC.addRelation(
 'users',
 () => ({
   resolver: UserTC.getResolver('findMany'),
   args: {
     filter: (source) => ({
       _operators: {
         _id: {
           in: source.reactions.map(reaction => reaction.user) || []
         }
       }
     }),
     skip: null,
     sort: null,
   },
   projection: { reactions: { user: true } },
 })
);

module.exports = schemaComposer.buildSchema();
```
I've tried several different ways of doing "addRelation". The above is based on what I could understand from the [following Github issue](https://github.com/graphql-compose/graphql-compose/issues/2).

PLEASE, I'd really appreciate and direction you can point me in! I'm having trouble understanding how this works.

**Comment by nodkz** [comment]
How I see you made the correct `PostTC.addRelation` definition. The problem in some other place. 

Firstly let simplify you relation. You may use `findByIds` resolver in such way:
```js
PostTC.addRelation(
 'users',
 () => ({
   resolver: UserTC.getResolver('findByIds'),
   args: {
     _ids: (source) => source.reactions.map(reaction => reaction.user) || [],
     skip: null,
     sort: null,
   },
   projection: { reactions: { user: true } },
 })
);
```

Then you need to check the correctness of providing users' ids in relation
```diff
-      _ids: (source) => source.reactions.map(reaction => reaction.user) || [],
+     _ids: (source) => {
+         const ids = source.reactions.map(reaction => reaction.user) || [];
+         console.dir(ids); // THERE should be such array [ObjectId('5ef...045'), ObjectId('5ef...045')]
+         return ids;
+     }
```
I'm strongly feeling that you got array of Users instead of array of users' ids. This happens due population of `.populate('reactions.details')` in `Mutation.postAddReaction` field.

I do not recommend to use`population` method with `graphql-compose-mongoose`. Cause under the hood mongoose changes field with Id by real Object. And it may bring unexpected behavior and complexity in problem diagnostic.

If it does not help you need to debug your resolver
```diff
-   resolve: ({ source, args, context, info }) => {
-     return Post.findOneAndUpdate({...}).populate('reactions.details');
+   resolve: async ({ source, args, context, info }) => {
+     const post = await Post.findOneAndUpdate({...}).populate('reactions.details');
+     console.dir(post); // this `post` will be used as `source` in your relation
+                                    // so check that `post.reactions.user` contains user ids instead of user Docs
+     return post;
```

Anyway all this code looks too complicated let's try to simplify it and build another relations. Do it in the next post.

**Comment by nodkz** [comment]
If `users` are connected with `reaction` type, so better will be to build relations there. Better not means that is correct solution for you product and API. Better here means that it's simplier.

It will looks something like this:
```js
const ReactionTC =  PostTC.getFieldTC('reactions');
const ReactionTC.addRelation({
   name: 'userDoc',
   () => ({
     resolver: UserTC.getResolver('findById'), // NOT findById
     args: {
       // source here is the `reaction` sub-doc
       _id: (source) => source.user,
     },
     projection: { user: true },
   })
});
```  
Then you may do following query:
```graphql
query {
  post {
     reactions {
       userDoc {
          _id
          first
          last
          email
       }
     }
  }
}
```

This solution is simpler in the code, but performance at runtime is not so good. Cause we use `findById` instead of `findByIds`.

**Comment by woh-dev** [comment]
@nodkz thanks for the fast response!

I tried both of your solutions listed above. I looks like the .addRelation is never called. I put a `console.dir `in both implementations and nothing is firing.

If I `console.log(ReactionTC.addRelation)` I get `[Function: addRelation]` so it is definitely there.

But if I change the code to something simple like...

```
ReactionTC.addRelation(
   'userDoc',
   () => console.log('test')
);

```
...I don't see anything firing either.

Any idea why this would be?

**Comment by woh-dev** [comment]
Also, to be clear, I removed all uses of .populate() from my code!

**Comment by nodkz** [comment]
It will be fired only in runtime. You should run graphql query where requested this relation.

**Comment by woh-dev** [comment]
When I run this query that you provided:

```
query {
  post {
     reactions {
       userDoc {
          _id
          first
          last
          email
       }
     }
  }
}
```
I get the following error: `"Cannot query field \"userDoc\" on type \"PostReactions\". Did you mean \"user\"?"`

I think you had a mistake in the ReactionTC.addRelation code that your provided? I've never seen the {name: 'userDoc' ... } format and it did not work for me so I it slightly to be as follows:

```
ReactionTC.addRelation(
  'userDoc',
   () => ({
     resolver: UserTC.getResolver('findById'), // NOT findById
     args: {
       // source here is the `reaction` sub-doc
       _id: (source) => source.user,
     },
     projection: { user: true },
   })
);
```

Is this correct? It does not appear to be running, even when I execute the query.

**Comment by nodkz** [comment]
Can you share your repo? Or clone https://github.com/graphql-compose/graphql-compose-boilerplate and put there your models.

It will be more productive.

**Comment by woh-dev** [comment]
@nodkz

I refactored some of your suggested code to use the 'prepareArgs' format instead of 'args' and everything is working perfectly now. Here is the .addRelation that I am now using:

```
ReactionTC.addRelation('userDetails', {
  resolver: () => UserTC.getResolver('findById'),
  prepareArgs: {
    _id: source => source.user,
    skip: null,
    sort: null,
  },
  projection: { user: true },
})
```

Your suggestion to create a _ReactionTC_ and do the .addRelation there is perfect for my needs. 

Thank you for speedy assistance and for all your work on GraphQL-Compose!

**Comment by nodkz** [comment]
@woh-dev my miss to not check addRelation semantic. I just take your example and rewrite it.

Of course in `.addRelation` should be `prepareArgs` property, not `args`. I edited your and my code above for further googlers.

Motivation to use `prepareArgs` instead of `args` in `.addRelation` method is that `args` already used in regular graphql resolvers, and behaviour of  `prepareArgs` differs. It will be wrong to use the same name `args` for different things.
