### ISSUE TITLE
Multitenancy MongoDB UseDB

### ISSUE THREAD

**Issue by AleksandarFaraj** [graphql-compose/graphql-compose-mongoose#114]
Hey,

I'm developing a B2B SaaS and I'm trying to reduce the possibility of information leaks. One strategy I want to do is to separate my customers by having a separate database (not separate database cluster). I'm wondering if this is possible to achieve with graphql-compose-mongoose? What makes it complicated is that mongoose does not support this and the mongodb-native driver requires that the schemas are remade for the new connection reference. 

Could I wrap a resolver and pass in my own model? 

https://github.com/Automattic/mongoose/issues/5746

**Comment by nodkz** [comment]
With your business strategy, I recommend to write resolvers yourself and do not use `graphql-compose`.

What solutions available now:
`graphql-compose` and `mongoose` supports different models on different connections. It means that you need to create different types for every connection. You have one UserSchema, but should create different models from this schema `UserConnectionA`, `UserConnectionB`. And so you will get different types for graphql.

Or you may create several schemas via `SchemaComposer` and for every client provide its graphql endpoint: https://site.com/graphql1, https://site.com/graphql2, https://site.com/graphql3
Or you may subtitute GraphQL schemas inside request.

Anyway, all these is  dirty solutions for you.

**Comment by AleksandarFaraj** [comment]
I appreciate the fast answer! I'll look into this more further down the road :p
