### ISSUE TITLE
calling `composeWithMongoose` on the `Model` breaks its `populate()` method for arrays

### ISSUE THREAD

**Issue by hedin-hiervard** [graphql-compose/graphql-compose-mongoose#117]
After you call `composeWithMongoose(Model)`, the populate method stops populating arrays (returns empty array instead).
The minimal repro repo: https://github.com/hedin-hiervard/graphql-compose-mongoose-bug

**Comment by nodkz** [comment]
With 4.4.2 works well?
In 4.5.0 I made some changes which may break this behavior. Very strange that tests did not catch any problem.

Many thanks for provided repro repo! Will help very well. Try to resolve it today, but I cannot promise ;)

**Comment by hedin-hiervard** [comment]
No, it doesn't work with 4.4.2 nor with 4.0.0

**Comment by nodkz** [comment]
Yeah, it's a very old bug. 
Found where it happens, will be fixed within an hour.

**Comment by nodkz** [comment]
Now will be published a new version, please try it.
Thanks for reporting!
