### ISSUE TITLE
Unexpected behavior from 'connection' resolver.

### ISSUE THREAD

**Issue by woh-dev** [graphql-compose/graphql-compose-mongoose#120]
It's been amazing working with _graphql-compose-mongoose_ over the last few weeks and discovering how powerful it is. Thank you for this incredible tool!

I am starting to use the 'connection' resolver that is built in to _grapqhl-compose-mongoose_, (not the plugin available at graphql-compose-connection). It works as expected when I use the forward pagination arguments `first` and `after`.

But when I try to paginate in reverse using `last` and `before` I get some unexpected behavior. 

Here's an example:

`(last: 2, before: "")`

```
r-0
r-1
r-2
r-3
r-4
r-5 
r-6 
r-7 
r-8 
r-9 <- result
r-10 <- result
```
I then try to get the next two pages.

`(last: 2, before: "r-9")`

```
r-0 <- actual result
r-1 <- actual result
r-2
r-3
r-4
r-5 
r-6 
r-7 <- expected result
r-8 <- expected result
r-9 
r-10 
```

Am I misunderstanding how this should work?

I saw this issue on the graphql-compose-connection docs.

graphql-compose/graphql-compose-connection#7

Is it possible that the fixes from this issue were not implemented in graphql-compose-mongoose?

**Comment by woh-dev** [comment]
I saw this issue on the grapqhl-compose-pagination docs. 

https://github.com/graphql-compose/graphql-compose-connection/issues/7

Is it possible that the fixes from this issue were not implemented in graphql-compose-mongoose?

**Comment by nodkz** [comment]
Hm, it's very strange.
Just added test case for [graphql-compose-connection](https://github.com/graphql-compose/graphql-compose-connection/commit/9da525a9b9e39ab54b4f804421df7f668616d657) It works as you describe with expected results.

I think the problem somewhere in this package (`graphql-compose-mongoose`). I'll try to look at on it tomorrow. Too tired today. 

Will be nice if you add broken test case here https://github.com/graphql-compose/graphql-compose-mongoose/tree/master/src/__tests__/guthub_issues with name 120-test.js 
It help me a lot to save time. Tnx.

**Comment by nodkz** [comment]
@woh-dev I resolved a problem. Please check and give me feedback - work it or not.

Please install `graphql-compose-connection@3.2.1` in your app. It has a problem with the fallback algorithm when `sort` argument not provided for backward connection.

Anyway, I recommend you to use `sort` argument when using connections. It helps to avoid overfetching/underfetching problem. Without sorting under the hood used limit/skip logic which not guarantee that you do not get the same records for next request.

**Comment by woh-dev** [comment]
Thanks, I went on vacation just after posting this, so I will take a look at this now!

**Comment by woh-dev** [comment]
@nodkz, to confirm --  the connection feature is now working correctly after I upgraded to ``` "graphql-compose-mongoose": "^5.0.0",```

Thank you thank you! Glad this bug was resolved so quickly!
