### ISSUE TITLE
Using connection on subfields?

### ISSUE THREAD

**Issue by woh-dev** [graphql-compose/graphql-compose-mongoose#125]
Is it possible to query for an item and paginate through a nested subarray using the ```connection``` resolver? 

Using```addRelation()``` this is easy, but in this case the comments are stored directly on the POST object, so there is no need to for ```addRelation()```.

Here is an example "POST" model schema:
```javascript
{
  caption: {
    type: String,
    trim: true,
    required: true
  },
  comments: [{
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    text: {
      type: String,
      required: true,
    }
  }],
  // References.
  author: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    index: true,
    required: true,
  },
}
```

I would like to be able to do any query or mutation on the PostTC and use ```connections``` to paginate through the nested comments. Something like this:

```javascript
query{
  postOne(filter: {_id: "5b7afccec19e5572fbf5f612"}) {
    author
    comments(before: "MQ==", last: 2) {
      edges {
        cursor
        node {
          text 
          user
        }
      }
    }
  }
}

```

Is this even possible? I'm hoping that I can keep the comments on the post object.

**Comment by nodkz** [comment]
Nope, it's not implemented. You need to do it yourself.

Maybe better to store comments in a separate collection?! 
Also don't miss limits for document size in MongoDB (how i remember it was 16MB, maybe something changed in new versions).

**Comment by woh-dev** [comment]
@nodkz, thanks for confirming this. I assumed but just wanted to make sure that I wasn't overlooking any relevant features of graphql-compose.

We were hoping to keep the comments in the same collection in this case because we don't expect large amounts of comments (16mb will be largely sufficient) and read times will be faster but it might make sense to switch to a new collection in order to benefit from ```connections```.

As always thanks for your help!
