### ISSUE TITLE
Wrap filter args

### ISSUE THREAD

**Issue by fklingler** [graphql-compose/graphql-compose-mongoose#129]
Hi!

I have this model:

```
const SchoolClassSchema = new Schema({
    name: { type: String, required: true },

    teacher: { type: Schema.Types.ObjectId, ref: 'User' },

    students: [{ type: Schema.Types.ObjectId, ref: 'User' }]
});
```

Teachers have a specific "user role". When a teacher makes a query or mutation on the User graph, I want to filter the results so that they only can do things on the students they teach to.

For that, I wrap the resolvers depending on their parameters. In case of a query/mutation with an `_id` param, I wrap with:

```
const userIds = await getUserIdsFromTaughtSchoolClasses(context.user);

if (!userIds.includes(args._id)) {
    args._id = null;
}
```

For query/mutations with `_ids` param, I wrap with:

```
const userIds = await getUserIdsFromTaughtSchoolClasses(context.user);

args._ids = args._ids.filter(id => userIds.includes(id));
```

The problem I have is for query/mutations that have a `filter` param. What should I do? I've been wanting to combine my filter with the original filter param using an AND clause, but I've come across this issue: https://github.com/graphql-compose/graphql-compose-mongoose/issues/128

Is there any other way to do this? I'd prefer to be able to add criterias to the mongo query directly!

If I also can improve the way I'm doing this for `_id` or `_ids` query/mutations, I'm open to suggestions!

**Comment by fklingler** [comment]
In a little bit more simple problem, on the SchoolClass graph I'd like to filter queries/mutations so that a Teacher (User with role) can only access classes they "own". What is the preferred way to do that?

**Comment by nodkz** [comment]
Please fork https://github.com/graphql-compose/graphql-compose-boilerplate

And add there your code. I ll try to review it tomorrow.

Any working repo helps us to resolve this problem much faster than on abstract code examples.

Thanks.

**Comment by fklingler** [comment]
I found the answer to my question, I just needed to use the `rawQuery` field of `resolveParams`, as it is interpreted when there is a `filter` param.

I can just do that:

```
        resolveParams.rawQuery = {
            $and: [
                (resolveParams.rawQuery || {}),
                { _id: { $in: userIds } }
            ]
        };
```
