### ISSUE TITLE
Are `lean` queries supported?

### ISSUE THREAD

**Issue by SnidelyWhiplash** [graphql-compose/graphql-compose-mongoose#140]
As I understand it, queries return fully instantiated Mongoose models by default. But you can override this if you just need the raw data, and don't plan on calling any instance methods, etc by using the `lean` option...

In my (limited) testing, it doesn't seem like that is supported in resolvers here..? I've tried both `Model.find({ query }, null, { lean: true })` and `Model.find({ query }).lean()` but it seems to prevent me from querying relational data. (It's been a while since I tested, I'm only just now circling back to this. I can provide fuller examples/errors if needed).

In the past, on REST projects, I've noticed *significant* performance impacts when querying for multiple documents without `lean`, and in my current GraphQL project I'm thinking this may also be the reason for slow query times.

Thanks for any insight!

**Comment by nodkz** [comment]
@SnidelyWhiplash sorry for late response. I was terribly busy with preparation for 2 conference talks and 2 active projects.

Let think what we can do with `lean`:
- Firstly it will be additional resolvers (cause lean breaks all virtual fields, hooks and custom logic from models)
- To move this feature, can you provide a test case 140-test.js via Pull Request in https://github.com/graphql-compose/graphql-compose-mongoose/tree/master/src/__tests__/guthub_issues folder? There are the bunch of other tests, which helps you to write a new one ;) We will resolve this feature inside your PR.

Thanks! Hope this problem is still actual for you.

**Comment by SnidelyWhiplash** [comment]
Hi @nodkz. This reply is incredibly delayed, sorry for that! We moved on to other issues, but now we're revisiting this.

I'll try to open a PR with a test, but I was curious if perhaps there has already been any movement on this feature? If my understanding is correct, using `.lean()`, especially when querying for multiple documents, is _significantly_ faster than not (anywhere from 3 - 10 times faster).

Thanks!

references:
https://www.tothenew.com/blog/high-performance-find-query-using-lean-in-mongoose-2/
https://mongoosejs.com/docs/tutorials/lean.html

**Comment by jdbdnz** [comment]
FWIW I don't think it needs to be an additional resolver @nodkz, an option which defaults to false is fine.
I consider it normal and expected that you cannot access Mongoose instance functions when using lean and would compose my queries accordingly.

**Comment by jdbdnz** [comment]
@SnidelyWhiplash I found a workaround. Albeit not perfect as it isn't a query option but instead specified during composition. 
```
tc.getResolver('findMany') .wrapResolve(next => resolveParams => next({
  ...resolveParams,
  beforeQuery: (query) => query.lean(),
}))
```

Check out this file for more context about how it works `src/resolvers/helpers/beforeQueryHelper.js` 

@nodkz a perfect solution IMO would be to add lean as a resolver argument.

**Comment by nodkz** [comment]
New lean-resolvers were added in `9.0.0-alpha.3`.

**Comment by nodkz** [comment]
`*Lean` resolvers were removed in favor of `{ lean: true}` config option in basic resolvers:
https://github.com/graphql-compose/graphql-compose-mongoose/issues/263#issuecomment-691477921
