### ISSUE TITLE
How to create mutation CreateOne with custom _id

### ISSUE THREAD

**Issue by asergiychuk** [graphql-compose/graphql-compose-mongoose#141]
Hi!
I need to create mutation CreateOne with custom _id, but CreateOne mutation remove _id from Input type.

How do it with right and easy way?

**Comment by nodkz** [comment]
This is an uncommon task.

So just copy https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/resolvers/createOne.js resolver and create a new one with another name in your code.
