### ISSUE TITLE
`source.X` null in `addRelation` if `source.X` not in query

### ISSUE THREAD

**Issue by calben** [graphql-compose/graphql-compose-mongoose#143]
Hullo everyone,

I have a confusing issue.
I have a `Student` and a `Counselor` where students can have a `counselorID` field.

```
const Student = mongoose.model('Student', {
    name: String,
    counselorID: Schema.Types.ObjectId,
});

const Counselor = mongoose.model('Counselor', {
    name: String,
    email: String,
});

StudentTC.addRelation('counselor', {
    resolver: () => CounselorTC.getResolver('findOne'),
    prepareArgs: {
        filter: source => ({
            _id: source.counselorID
        })
    }
});
```

For the most part, my counselor relation works!
But it only works if counselorID is also in the query.

So this works:

```
query {
  studentMany(filter:{}) {
    _id
    counselorID
    counselor {
      name
    }
  }
}
```

But this does not:

```
query {
  studentMany(filter:{}) {
    _id
    counselor {
      name
    }
  }
}
```

Looking at the Mongoose debug, if the counselorID is not in the query then the query ends up being `Mongoose: counselors.findOne({ _id: undefined }, { projection: { name: true } })`.

I'm having difficulty figuring out what's causing this!
What did I bugger up?

Thanks for any help!

**Comment by nodkz** [comment]
You need to consult graphql-compose-mongoose to request additional fields via `projection` property when you request just `conselor` field.

You may do it in such way:
```diff
StudentTC.addRelation('counselor', {
    resolver: () => CounselorTC.getResolver('findOne'),
    prepareArgs: {
        filter: source => ({
            _id: source.counselorID
        })
    },
+    projection: { counselorID: true }
});
```

**Comment by calben** [comment]
I see; thanks a lot!
