### ISSUE TITLE
How to recompose 

### ISSUE THREAD

**Issue by israelglar** [graphql-compose/graphql-compose-mongoose#148]
Hello,

I have an application that needs to change one mongoose model in compile time and I can't find a way to do that.

### Example

I have an Account model that has this schema:
```ts
export const AccountSchema = new Schema(
  {
    email: {
      type: String,
      unique: 'Two accounts cannot share the same email (VALUE)',
      required: true,
    },
    username: {type: String, required: true},
    name: {type: String, required: true},
  },
  {
    timestamps: true,
  },
);

export const AccountModel = model<IAccount>('Account', AccountSchema);

composeWithMongoose(AccountModel, {});
```

Then somewhere else this is done: 
```ts
let schema = AccountModel;
let model = AccountModel; 

schema.add(...);
# this are some "hacks" that deletes the entry from the singleton
schemaComposer.delete(model.schema);
delete Mongoose.models[args.info.name];
model = modelFn<T>(args.info.name, schema);

composeWithMongoose(model, {});
```

What ends up happening on graphql is that I have a type Account that it's right:
```ts
type Account {
email: Email
username: String
name: String
_id: MongoID!
updatedAt: Date
createdAt: Date
helldfadso: String
aassa: String
}
```

But the Inputs and Filters that are derived from it are not:
```ts
type UpdateByIdAccountInput {
email: String
username: String
name: String
_id: MongoID!
updatedAt: Date
createdAt: Date
}
```

Have any clue why it's happening or is there another way to do this? 

Thanks!

Edit:
What I've found was that when I do `composeWithMongoose`  for the second time, the TypeComposer Fields don't match the InputTypeComposer Fields.
I'm running:
```ts
console.log(Object.keys(tc.getFields()).length, Object.keys(tc.getInputTypeComposer().getFields()).length)
```
The model account has 6 fields in total and when run the function for the first time the result is `6, 6`
But when I add 2 fields to the schema and run the compose again the result is `8, 6`

The TC updates but not the ITC

**Comment by nodkz** [comment]
Graphql-compose-mongose did not designed for such cases - when you create a mongoose model and then change it. Internally it caches all generated types in schemaComposer.

TC should be generated once and then you may change its types manually via graphql-compose methods. 

In your case you should remove all generated types (more than 50 types) from first run in schemaComposer before generating TC in the second time. Otherwise it will reuse existed types.

Or you may choose different type name when generating types

```js
composeWithMongoose(AccountModel, { name: 'AccountFirst' });

... your mongoose model modification...

composeWithMongoose(AccountModel, { name: 'AccountSecond' });
```

**Comment by israelglar** [comment]
Oh okay! I thought that it was possible.. Thanks for the information :) I will try setting it with a different name or some other solution

**Comment by ChrisLahaye** [comment]
@israelglar @nodkz How did you solve this issue? It always takes the name of the first use.

**Comment by Abenezer** [comment]
is there any way i can do this with the version 9.  changing the type names will not be an option because every  ITC ( filter and input ) will have different name and we dont want that for any frontend
