### ISSUE TITLE
Remove field from InputTypes

### ISSUE THREAD

**Issue by israelglar** [graphql-compose/graphql-compose-mongoose#150]
My model  has a property that is set and managed by system:
```ts
export const ExampleSchema = new Schema(
  {
    canChange: {
      type: String,
    },
    systemVar: {
      type: String,
    }
);
```

I want to remove `systemVar` from all input types, so that the user can see it when he queries the model, but can't modify it.

I tried to to 

```ts
const tc = composeWithMongoose(ExampleModel, {});
tc.getITC().removeField('systemVar');
``

But that doesn't methods's arguments. 
What I'm looking for is to be able to remove a field from the InputTypeComposer and that to remove the fields from all the method's arguments. 

Example:
#### Expected result:
```ts
type Example {
  canChange: String
  systemVar: String
}

type CreateOneExampleInput {
  canChange: String
}
```

If that is not possible yet and you think that it's a viable option to have in the library, I can try and contribute with a PR.

**Comment by nodkz** [comment]
You need to modify every used resolver manually:
```js
const CreateOneRecordITC = tc.getResolver('createOne').getArgTC('record');
CreateOneRecordITC.removeField('systemVar');
```

### PROPOSAL, not implemented yet 

It can be improved by allowing to remove nesting arguments via dot-notation. Something like 
```js
 tc.getResolver('createOne').removeArg('record.systemVar');
```
@israelglar will be cool if you add such ability

**Comment by nodkz** [comment]
TypeComposer already has similar logic with `addNestedFields` method:
https://github.com/graphql-compose/graphql-compose/blob/6481fe5f978c4afa3807ffc7af338f3e18f832b8/src/TypeComposer.js#L332-L360

Where it detects dots in field names and create intermediate types or use existed types.

**Comment by israelglar** [comment]
I was trying to avoid removing from every resolver, because I would have to be mindful of that when creating new Resolvers as well.. 

Do you think that by removing the field from InputTypeComposer and make that remove the field from all input type a bad option?

I think it's intuitive and can help a lot for simplicity.

I can do a PR for that

**Comment by nodkz** [comment]
For now, hiding fields globally from input types can be done via https://github.com/graphql-compose/graphql-compose-mongoose#customization-options

Every resolver creates its own Input types for further modifications. It helps to tune schema as you wish after generation. And changing eg. createOne resolver will not break other resolvers.

So if you want to change generated types and resolvers, you SHOULD do it for every resolver.  To do this task you may
- write helper methods in your code
- may improve existed methods in graphql-compose via PR (like allowing removeFields via dot-notation).

PS. Already generated ITC from TC exists only for cloning purposes. And its modification should not affect on existed types.

**Comment by israelglar** [comment]
Thanks for the response!
Setting the configuration did  work :+1: 
```ts
{
    inputType: {
      fields: {
        remove: ["systemVar"]
      }
    }
  }
```

About  remove nesting arguments via dot-notation, I will have that on my TODO list :) When I find time I will try to make a PR and add that functionality, :)
