### ISSUE TITLE
Optional enum error

### ISSUE THREAD

**Issue by cmckni3** [graphql-compose/graphql-compose-mongoose#157]
db model:

```
const mongoose = require('mongoose');

const { Schema } = mongoose;

module.exports = mongoose.model(
  'visit',
  new Schema({
    url: { type: String, required: true },
    referredBy: { type: String, enum: ['WEBSITE', 'NEWSPAPER'] },
  })
);
```

```
Expected a value of type "EnumvisitReferredBy" but received: 
```

I came up with a contrived example and you could say another value could be added to `referredBy`. In my app, I need to be able to specify `''` and `null` though.

**Comment by nodkz** [comment]
As a start point, you may use the following test case
https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/__tests__/guthub_issues/157-test.js#L45-L49

You may extend any type in your schema after generation. By graphql spec enum types cannot have `''` and `null` as keys. But can be used as values on your server side (see test case).

**Comment by cmckni3** [comment]
Thanks. I handled this by modifying the field's TC.
