### ISSUE TITLE
Authentication & Authorization: Easier than Expected

### ISSUE THREAD

**Issue by coommark** [graphql-compose/graphql-compose-mongoose#158]
So not only is this package so super awesome, it saved me weeks of coding, especially graphql to mongoose relationships and all those resolvers code! 

But here is the really other super cool thing: **Authentication and authorization** is super easy too! So I will leave this here for other users who may be looking for authentication & authorization flow using this package. (**NOTE:** I am like only a week old using Graphql - that because my wife insisted the new e-commerce application should use qraphql not REST. Women can make husbands do stuff - trust me!)

Now so my first struggle was authentication and authorization, and after about 10 hours straight evaluating `graphql-compose-mongoose`, I found out it was really easy to achieve.

**My situation  - build a large e-commerce application using:**

1. Node/Express server
2. Graphql
3. Next.JS (React) front-end
4. Elasticsearch, etc

**My Experience:**
One week old using Graphql
Less than one day experience with `graphql-compose-mongoose`

**Authentication flow:**
1. Build your regular Express & JWT authentication app
2. Send access token to front-end app
3. Return access token to server during graphql calls (you can return it in a header or cookie)
4. Create an Express middleware to check if user is authenticated, and add the appropriate auth headers to the `req `object
5. Import the middleware and use it in the express server startup file. See these two below:

```
//middleware/is-auth.js
import jwt from 'jsonwebtoken';

export default (req, res, next) => {
    const token = req.headers['x-auth-token'];
    if(!token || token ==='') {
        req.isAuth = false;
        return next();
    }
    let decodedToken;
    try {
        decodedToken = jwt.verify(token, process.env.JWT_SECRET)
    } catch(err) {
        req.isAuth = false;
        return next();
    };
    req.isAuth = true;
    req.appRoles = decodedToken.appRoles;
    req.userId = decodedToken.userId;
    next();
}
```
Please NOTE the code in BOLD
```
//Server app.js (or server.js)
require('dotenv').config();
import express from 'express';
import graphqlHttp from 'express-graphql';
import bodyParser from 'body-parser';
import cookieParser from 'cookie-parser';
import mongoose from 'mongoose';
import cors from 'cors'
import schema from './graphql/schema'
**import isAuth from './middleware/is-auth';**

const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use(cookieParser());
**app.use(isAuth);**

**app.use('/graphql', graphqlHttp(async (req) => ({
    schema: schema,
    graphiql: true,
    context: {
        req,
    },
})));**

app.get('/api/check', (req, res, next) => {
    res.send('API is running...');
})

mongoose.connect(
    `mongodb://${process.env.MONGO_HOST}:${process.env.MONGO_PORT}/${process.env.MONGO_DB}`
).then(() => {
    app.listen(process.env.PORT, process.env.HOST, () =>
        console.log(`API running at ${process.env.HOST}:${process.env.PORT}`)
    );
}).catch((err) => {
    console.log(err)
});
```

**Explanation:**
1. Import the isAuth middleware into the express app
2. Apply it to the entire app
3. Attach the req object to the context, so that it is available to the entire graphql endpoints

Now to restrict access to certain endpoints (mutations or queries), do these:
Create a wrapper function like below:

//is-auth.js
```
export default (resolvers) => {
    Object.keys(resolvers).forEach((k) => {
        resolvers[k] = resolvers[k].wrapResolve(next => async rp => {
            if(!rp.context.req.isAuth) {
                throw new Error('You must login to view this.');
            }
            return next(rp)
        })
    })
    return resolvers
}
```

Import the function into your schema and use:

```
import { schemaComposer } from 'graphql-compose';
import { UserTC } from '../models/user-management/user';
import { ApplicationRoleTC } from '../models/user-management/applicationRole';
import authOnly from '../middleware/auth-only';

schemaComposer.Query.addFields({
    //Users
    userById: UserTC.getResolver('findById'),
    userByIds: UserTC.getResolver('findByIds'),

    //Application Roles
    **...authOnly({
        applicationRoleMany: ApplicationRoleTC.getResolver('findMany'),
    }),**
});

schemaComposer.Mutation.addFields({
    login: UserTC.getResolver('login'),
});

const graphqlSchema = schemaComposer.buildSchema();
export default graphqlSchema;
```

And voila, `applicationRoleMany `can only be accessed by authenticated users!

**PS:** As you can see above, I have a mutation called login, let me share the entire User model below:

```
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { autoIncrement } from 'mongoose-plugin-autoinc';
import { composeWithMongoose } from 'graphql-compose-mongoose';
import { ShopTC } from '../seller-management/shop';

const Schema = mongoose.Schema;

const userSchema = new Schema({
    firstName: {
        type: String,
        required: true
    },
    otherNames: {
        type: String,
        required: false
    },
    phone: {
        type: Number,
        required: true
    },
    email: {
        type: String,
        required: true,
        unique: true
    },
    password: {
        type: String,
        required: true
    },
    countryCode: {
        type: String,
        required: true
    },
    createdShops: [
        {
            type: Number,
            ref: 'Shop'
        }
    ],
    applicationRoles: [
        {
            type: Number,
            ref: 'ApplicationRole'
        }
    ],
    adminInShops: [
        {
            type: Number,
            ref: 'Shop'
        }
    ]
},{timestamps: true});
userSchema.plugin(autoIncrement, {
    model: 'User',
    startAt: 1,
    incrementBy: 1
});

export const User = mongoose.model('User', userSchema);
const customizationOptions = {};
export const UserTC = composeWithMongoose(User, customizationOptions);

UserTC.addFields({
    token: {
        type: 'String',
        description: 'Token of authenticated user.'
    }
})
UserTC.addRelation(
    'createdShops', {
        resolver: () => ShopTC.getResolver('findByIds'),
        prepareArgs: {
            _ids: (source) => source.createdShops,
        },
        projection: { createdShops: 1 }
    }
);

UserTC.addResolver({
    kind: 'mutation',
    name: 'login',
    args: {
        identity: 'String!',
        password: 'String!',
    },
    type: UserTC.getResolver('updateById').getType(),
    resolve: async({args, context}) => {
        console.log(context.req.isAuth)
        let user = null;
        if(isNaN(Number(args.identity))){
            user = await User.findOne({ email: args.identity });
        } else {
            user = await User.findOne({ phone: Number(args.identity) });
        }

        if(!user) {
            throw new Error('User does not exist.')
        }
        const isEqual = await bcrypt.compare(args.password, user.password);
        if(!isEqual) {
            throw new Error('Password is not correct.');
        }
        const token = jwt.sign({userId: user.id}, process.env.JWT_SECRET, {
            expiresIn: '24h'
        });
        return {
            recordId: user._id,
            record: {
                email: user.email,
                token: token,
                createdShops: user.createdShops,
            }
        }
    }
})
```

**What about Authorization?**
Well, you can create exactly something like the `is-auth.js ` function above, check if the user has the roles to access the endpoint and act accordingly. 

**Final Thoughts:**
All the credit for this awesomeness goes to the creators of this package for providing the ability to create wrappers for resolvers. How easier can it get??? **YOU GUYS ROCK!**

**Verify?**
Is this flow good or is there a better way to achieve same?

**Comment by nodkz** [comment]
JWT is insecure if tokens are stollen (there is no good way to invalidate stolen tokens).

**You correctly using the resolver wrapping!** 👍
Thanks for the detailed explanation it will be helpful for further googlers. BTW you may consider publishing this as an article on medium 😉

----------

In future (no ETA) I'll improve resolvers which will work in the following manner [JUST PROPOSAL]:
```js
schemaComposer.Query.addFields({
    userById: UserTC.getResolver('findById', [authMiddleware]),
    userByIds: UserTC.getResolver('findByIds', [authMiddleware]),
});

async function authMiddleware(resolve, source, args, context, info) {
  if (somehowCheckAuthInContext(context)) {
     return resolve(source, args, context, info);
  }
  throw new Error('You must be authorized');
}
```

Such design helps to reuse existed middlewares already written for Prisma (https://www.prisma.io/blog/graphql-middleware-zie3iphithxy) or write a new one.

**Comment by nodkz** [comment]
**FRESH UPDATES** 😜

In graphql-compose@5.10.0 implemented Prisma design middlewares. 
Such design helps to reuse existed middlewares already written for Prisma (https://www.prisma.io/blog/graphql-middleware-zie3iphithxy) or easily write a new one.

Try a new approach:

```js
schemaComposer.Query.addFields({
    userById: UserTC.getResolver('findById', [authMiddleware]),
    userByIds: UserTC.getResolver('findByIds', [authMiddleware]),
});

async function authMiddleware(resolve, source, args, context, info) {
  if (somehowCheckAuthInContext(context)) {
     return resolve(source, args, context, info);
  }
  throw new Error('You must be authorized');
}
```

**Comment by coommark** [comment]
@nodkz Thank you for pointing out this other approach. I upgraded to graphql-compose@5.10.0 and voila - another way to achieve same result!

BTW I use another of your cool [packages](https://github.com/nodkz/mongoose-plugin-autoinc).

**Comment by coommark** [comment]
I just realized I didn't ask @nodkz, what do you suggest I use other than JWT? Sure I don't want to create an entire authentication server which stores tokens and can invalidate them. Similarly, there are only as many paid services I want to use, definitely I don't want to pay for account management, plus:

1. I want users to login either by phone number or email
2. I will have an Android and iOS apps using the same api
3. My application is setup to with [express-http-proxy](https://github.com/villadora/express-http-proxy) running on port 8080, which in turn proxies all requests to /admin to an admin backend with and admin theme, / to a Next.js frontend, /graphql to a graphql server and /search to an Elasticsearch server. ALL THESE WILL SHARE SAME TOKEN SENT IN HEADERS
4. All payment requests will have a 2 factor verification process where requestee must validate request by imputing a one time password (OTP)

What will you suggest?

**PS:** Ok so to update this for anyone implementing JWT for authentication using the middleware pattern, my graphql-middleware is:

```
export const isAuthenticated = async (resolve, root, args, context, info) => {
    if(!context.req.isAuth) {
        throw new Error(context.req.errorMessage);
    }
    const result = await resolve(root, args, context, info)
    return result
}
```

And the resolver becomes:
`applicationRoleMany: ApplicationRoleTC.getResolver('findMany', [isAuthenticated]),`

Just updated the express middleware to add more descriptive error messages:
import jwt from 'jsonwebtoken';

```
export default (req, res, next) => {
    const token = req.headers['x-auth-token'];
    if(!token || token ==='') {
        req.isAuth = false;
        req.errorMessage = "You must login to view this."
        return next();
    }
    let decodedToken;
    try {
        decodedToken = jwt.verify(token, process.env.JWT_SECRET)
    } catch(err) {
        req.isAuth = false;
        req.errorMessage = "Invalid token. Please re-login to continue."
        return next();
    };
    req.isAuth = true;
    req.appRoles = decodedToken.appRoles;
    req.userId = decodedToken.userId;
    next();
}
```
And you need to `yarn add graphql-middleware` and import the two in the schema file:
```
import { isAuthenticated } from '../middleware/authorization';
import { applyMiddleware } from 'graphql-middleware';
```

**Comment by Quinton** [comment]
`that because my wife insisted the new e-commerce application should use qraphql not REST. Women can make husbands do stuff - trust me!` LOL

**Comment by YannisMarios** [comment]
@coommark So where do you  use "applyMiddleware"?

**Comment by obernal** [comment]
> **FRESH UPDATES** 😜
> 
> In graphql-compose@5.10.0 implemented Prisma design middlewares.
> Such design helps to reuse existed middlewares already written for Prisma (https://www.prisma.io/blog/graphql-middleware-zie3iphithxy) or easily write a new one.
> 
> Try a new approach:
> 
> ```js
> schemaComposer.Query.addFields({
>     userById: UserTC.getResolver('findById', [authMiddleware]),
>     userByIds: UserTC.getResolver('findByIds', [authMiddleware]),
> });
> 
> async function authMiddleware(resolve, source, args, context, info) {
>   if (somehowCheckAuthInContext(context)) {
>      return resolve(source, args, context, info);
>   }
>   throw new Error('You must be authorized');
> }
> ```

@nodkz How would this work with the new resolver creation method using `mongooseResolvers` ? 
Thanks!

**Comment by nodkz** [comment]
Became a little bit verbose.

```ts
schemaComposer.Query.addFields({
    userById: UserTC.mongooseResolvers.findById().withMiddlewares([authMiddleware]),
    userByIds: UserTC.mongooseResolvers.findByIds().withMiddlewares([authMiddleware]),
});
```

This verbosity helps to provide the following advantages:
- You may programmatically modify TypeComposer and only after that generate resolvers with their sub-types based on already customized fields in TypeComposer.
- Safe memory and time on the bootstrap server phase, because it won't generate unused resolvers.
- You may call one resolver generator several times with different configurations.
mongooseResolvers factory has improved typescript definitions. And you will get not only a list of available resolvers by names but also their customization options. Moreover, all generated Resolvers will know its source: Model<IDoc>.
- According to the customization options for each resolver, you may control how your resolvers will be generated. Also, it unlocks the ability in future releases to add more options like before & after hooks, ACL, additional filters, and sorts params.

**Comment by nodkz** [comment]
@obernal middlewares with graphql-compose-mongose@9.0.0 can be used in the following manner:

```ts
schemaComposer.Query.addFields({
    userById: UserTC.mongooseResolvers.findById().withMiddlewares([authMiddleware]),
    userByIds: UserTC.mongooseResolvers.findByIds().withMiddlewares([authMiddleware]),
});
```

This verbosity helps to provide the following advantages:
- You may programmatically modify TypeComposer and only after that generate resolvers with their sub-types based on already customized fields in TypeComposer.
- Safe memory and time on the bootstrap server phase, because it won't generate unused resolvers.
- You may call one resolver generator several times with different configurations.
mongooseResolvers factory has improved typescript definitions. And you will get not only a list of available resolvers by names but also their customization options. Moreover, all generated Resolvers will know its source: Model<IDoc>.
- According to the customization options for each resolver, you may control how your resolvers will be generated. Also, it unlocks the ability in future releases to add more options like before & after hooks, ACL, additional filters, and sorts params.

**Comment by obernal** [comment]
Awesome! Thanks for the detailed response and all the great work with `graphql-compose-mongoose` !

**Comment by SithGit** [comment]
This is my token verification code (this code is working find for the Rest API)
![ddadadad](https://user-images.githubusercontent.com/17455101/108361703-693e9e80-7225-11eb-9897-964827f96797.png)

and this one is the place I put the code to do a verification.
![file](https://user-images.githubusercontent.com/17455101/108361889-a1de7800-7225-11eb-887a-c89ea95d0c54.png)

once I tried to send the query I got this Error instead;
![err](https://user-images.githubusercontent.com/17455101/108362015-cc303580-7225-11eb-987a-dcd29d9097af.png)

What should I do?

**Comment by theciphedwolf** [comment]
> **FRESH UPDATES** 😜
> 
> In graphql-compose@5.10.0 implemented Prisma design middlewares.
> Such design helps to reuse existed middlewares already written for Prisma (https://www.prisma.io/blog/graphql-middleware-zie3iphithxy) or easily write a new one.
> 
> Try a new approach:
> 
> ```js
> schemaComposer.Query.addFields({
>     userById: UserTC.getResolver('findById', [authMiddleware]),
>     userByIds: UserTC.getResolver('findByIds', [authMiddleware]),
> });
> 
> async function authMiddleware(resolve, source, args, context, info) {
>   if (somehowCheckAuthInContext(context)) {
>      return resolve(source, args, context, info);
>   }
>   throw new Error('You must be authorized');
> }
> ```

I'm Trying this approach but query returns null every single time. Without middleware it works fine
 
```js 
    userMany: UserTC.getResolver("findMany", [
    async (next, source, args, context, info) => {
      protect(next, context, args, context, info);
    },
  ]),

//Here is My Middleware Code 

exports.protect = async (next, context, args) => {
  const { req } = context;
  let token;
  if (
    req &&
    req.headers.authorization &&
    req.headers.authorization.startsWith("Bearer")
  ) {
    token = req.headers.authorization.split(" ")[1];
    console.log(token);
  }

  if (!token) {
    throw new Error("Not Authorized");
  }

  // 2) Verification token
  const decoded = await promisify(jwt.verify)(token, process.env.JWT_SECRET);

  // 3) Check if user still exists
  const currentUser = await User.findById(decoded.id);
  if (!currentUser) {
    return next(
      new AppError(
        "The user belonging to this token does no longer exist.",
        401
      )
    );
  }

  // 4) Check if user changed password after the token was issued
  if (currentUser.changedPasswordAfter(decoded.iat)) {
    return next(
      new AppError("User recently changed password! Please log in again.", 401)
    );
  }

  // GRANT ACCESS TO PROTECTED ROUTE
  req.user = currentUser;
  return next(args,context);
};
```

**Comment by nodkz** [comment]
@theciphedwolf you should correctly use all 5 arguments in strict order.  context is the 4th argument

async function authMiddleware(next, source, args, context, info) {
  if (somehowCheckAuthInContext(context)) {
     return next(source, args, context, info);
  }
  throw new Error('You must be authorized');
}

**Comment by theciphedwolf** [comment]
Yeah I fixed It :') Thanks 😊

**Comment by rafaneri** [comment]
@nodkz, is it possible to control access to certain fields within the middleware function?

**Comment by nodkz** [comment]
@rafaneri no, right now there is no convenient way to apply middleware function to certain fields.

According to your case and codebase can you provide a desired way how you want to apply it?
Via config options in resolvers, or maybe via a special method in TypeComposer, or any other way. It does not difficult to implement, difficult to invent a convenient way/design.

**Comment by rafaneri** [comment]
@nodkz I have a generic resolver for all my entities.

This is my *generic.resolver.ts* class.

```typescript
/* eslint-disable @typescript-eslint/no-empty-function */
import { AnyParamConstructor } from '@typegoose/typegoose/lib/types'
import { ObjectTypeComposerWithMongooseResolvers } from 'graphql-compose-mongoose'
import { GenericService } from './generic.service'
import { GenericEntity } from './entities/generic.entity'
import { GenericHelper } from './generic.helper'
import schemaComposer from '../config/graphql/schemaComposer'
import { camelCase, pascalCase } from 'change-case'
import { plural } from 'pluralize'
import { GraphQLSchema } from 'graphql'
import pubsub from '../config/graphql/pubSub'
import { RedisPubSub } from 'graphql-redis-subscriptions'
import { ResolverEvent } from '../events/resolver-event'
import { PermissionManager } from '../permission/permission.manager'
import { AuthorizationMiddleware } from 'src/common/middleware/authorization.middleware'

export enum QUERY {
	COUNT = 'count',
	FIND_BY_ID = 'findById',
	FIND_BY_IDS = 'findByIds',
	FIND_ONE = 'findOne',
	FIND_MANY = 'findMany',
	DATA_LOADER = 'dataLoader',
	DATA_LOADER_MANY = 'dataLoaderMany',
	PAGINATION = 'pagination',
	CONNECTION = 'connection'
}

export enum MUTATION {
	CREATE_ONE = 'createOne',
	CREATE_MANY = 'createMany',
	UPDATE_BY_ID = 'updateById',
	UPDATE_ONE = 'updateOne',
	UPDATE_MANY = 'updateMany',
	REMOVE_BY_ID = 'removeById',
	REMOVE_ONE = 'removeOne',
	REMOVE_MANY = 'removeMany'
}

export class GenericResolver<T extends GenericEntity> {
	protected pubsub: RedisPubSub
	protected readonly cls: AnyParamConstructor<T>
	protected readonly tc: ObjectTypeComposerWithMongooseResolvers<any, any>

	constructor(
		cl: AnyParamConstructor<T>,
		readonly service?: GenericService<T>
	) {
		this.cls = cl
		if (!service) {
			this.service = new GenericService<T>(cl)
		}
		this.tc = GenericHelper.getObjectTypeComposer(cl.name)

		this.pubsub = pubsub

		this.setupCustomResolvers()
		this.bindDefaultResolvers()
		this.addDefaultRelations()
		this.addRelations()
		this.buildSchema()
	}

	buildSchema(): GraphQLSchema {
		return schemaComposer.buildSchema()
	}

	addDefaultRelations() {
		const schemaTree = this.getService().getSchemaTree()
		Object.keys(schemaTree).forEach(key => {
			let value = schemaTree[key]
			const isArray = Array.isArray(value.type)
			if (isArray) {
				const nValue = value.type[0]
				value = nValue
			}
			let remoteTC
			if (
				value.ref &&
				(remoteTC = GenericHelper.getObjectTypeComposer(value.ref)) &&
				remoteTC.getResolver
			) {
				const projection = {}
				projection[key] = 1
				const relationName = isArray
					? plural(camelCase(value.ref))
					: camelCase(value.ref)
				let opts: any

				if (isArray) {
					opts = {
						resolver: () => remoteTC.getResolver(QUERY.FIND_BY_IDS),
						prepareArgs: {
							_ids: source => source[key]
						},
						projection
					}
				} else {
					opts = {
						resolver: () => remoteTC.getResolver(QUERY.FIND_BY_ID),
						prepareArgs: {
							_id: source => source[key]
						},
						projection
					}
				}

				this.tc.addRelation(`${relationName}`, opts)
			}
		})
	}

	private defaultResolvers = {
		query: {
			ById: QUERY.FIND_BY_ID,
			FindOne: QUERY.FIND_ONE,
			Many: QUERY.FIND_MANY,
			Count: QUERY.COUNT,
			Connection: QUERY.CONNECTION,
			Pagination: QUERY.PAGINATION
		},
		mutation: {
			CreateOne: MUTATION.CREATE_ONE,
			UpdateById: MUTATION.UPDATE_BY_ID,
			RemoveById: MUTATION.REMOVE_BY_ID
		}
	}
	private query = {}
	private mutation = {}

	protected beforeBindDefaultResolvers() {}
	protected afterBindDefaultResolvers() {}

	protected bindDefaultResolvers() {
		this.beforeBindDefaultResolvers()

		Object.keys(this.defaultResolvers.query).forEach((key, i) => {
			this.query[`${this.cls.name}${key}`] = this.tc.getResolver(
				Object.values(this.defaultResolvers.query)[i],
				[AuthorizationMiddleware]
			)
			const re = new ResolverEvent(
				`${this.cls.name}${key}`,
				this.cls.name,
				this.query[`${this.cls.name}${key}`].description
			)
			PermissionManager.create(re)
		})

		Object.keys(this.defaultResolvers.mutation).forEach((key, i) => {
			this.mutation[
				`${this.cls.name}${key}`
			] = this.tc.getResolver(
				Object.values(this.defaultResolvers.mutation)[i],
				[AuthorizationMiddleware]
			)
			const re = new ResolverEvent(
				`${this.cls.name}${key}`,
				this.cls.name,
				this.mutation[`${this.cls.name}${key}`].description
			)
			PermissionManager.create(re)
		})

		this.afterBindDefaultResolvers()
		schemaComposer.Query.addFields(this.query)
		schemaComposer.Mutation.addFields(this.mutation)
	}

	protected addMutationMiddlewares(
		mutationName: string | MUTATION,
		middlewares: Array<any>
	) {
		this.mutation[
			`${this.cls.name}${pascalCase(mutationName)}`
		] = this.mutation[
			`${this.cls.name}${pascalCase(mutationName)}`
		].withMiddlewares(middlewares)
	}

	protected addSubscription(subscription): void {
		schemaComposer.Subscription.addFields(subscription)
	}

	protected addQuery(queryName: string, resolverName?: string | QUERY) {
		this.defaultResolvers.query[queryName] = resolverName ?? queryName
	}

	protected removeQuery(...queries: string[] | QUERY[]) {
		queries.forEach(queryName => {
			const index = Object.values(this.defaultResolvers.query).findIndex(
				e => e === queryName
			)
			const key = Object.keys(this.defaultResolvers.query)[index]
			delete this.defaultResolvers.query[key]
			const re = new ResolverEvent(key, this.cls.name)
			PermissionManager.remove(re)
		})
	}

	protected addMutation(
		mutationName: string,
		resolverName?: string | MUTATION
	) {
		this.defaultResolvers.mutation[mutationName] = resolverName ?? mutationName
	}

	protected removeMutation(...mutations: string[] | MUTATION[]) {
		mutations.forEach(mutationName => {
			const index = Object.values(this.defaultResolvers.mutation).findIndex(
				e => e === mutationName
			)
			const key = Object.keys(this.defaultResolvers.mutation)[index]
			delete this.defaultResolvers.mutation[key]
			const re = new ResolverEvent(key, this.cls.name)
			PermissionManager.remove(re)
		})
	}

	protected clearDefaultResolvers(): void {
		this.clearDefaultQueries()
		this.clearDefaultMutations()
	}

	protected clearDefaultQueries(): void {
		this.removeQuery(
			QUERY.FIND_BY_ID,
			QUERY.FIND_MANY,
			QUERY.COUNT,
			QUERY.CONNECTION,
			QUERY.PAGINATION
		)
	}

	protected clearDefaultMutations(): void {
		this.removeMutation(
			MUTATION.CREATE_ONE,
			MUTATION.UPDATE_BY_ID,
			MUTATION.REMOVE_BY_ID
		)
	}

	setupCustomResolvers() {}

	addRelations() {}

	getObjectTypeComposer(): ObjectTypeComposerWithMongooseResolvers<any, any> {
		return this.tc
	}

	getService(): GenericService<T> {
		return this.service
	}
}

```


This is my *AuthorizationMiddleware* function. 
My idea is put here something to filter the fields depending of the user rule.

```typescript
import { AUTH } from '@environments'
import { UnauthorizedException } from '@nestjs/common'
import { PermissionManager } from '../../permission/permission.manager'

export async function AuthorizationMiddleware(
	resolve,
	source,
	args,
	context,
	info
): Promise<any> {
	if (AUTH) {
		const canAccess = await PermissionManager.canAccess(
			context.currentUser,
			info.fieldName
		)
		if (canAccess) {
// my idea is put here something to filter the fields depending of the user rule
			return resolve(source, args, context, info)
		}
		throw new UnauthorizedException()
	}
	return resolve(source, args, context, info)
}

```

**Comment by rafaneri** [comment]
@nodkz, solved. I'm using the middlewares to solve the question.

```typescript
this.query[`${this.cls.name}${key}`] = this.tc.getResolver(
				Object.values(this.defaultResolvers.query)[i],
				[AuthorizationMiddleware]
			)
```
