### ISSUE TITLE
relations efficiency 

### ISSUE THREAD

**Issue by wizardnet972** [graphql-compose/graphql-compose-mongoose#162]
In readme, [How to build nesting/relations?](https://github.com/graphql-compose/graphql-compose-mongoose#how-to-build-nestingrelations), says that relations go like this:
```
UserTC.addRelation(
  'friends',
  {
    resolver: () => UserTC.getResolver('findByIds'),
    prepareArgs: { // resolver `findByIds` has `_ids` arg, let provide value to it
      _ids: (source) => source.friendsIds,
    },
    projection: { friendsIds: 1 }, // point fields in source object, which should be fetched from DB
  }
);
```

This is mean that `graphql-compose-mongoose` execute `.find` **then for each property** it's run `.findByIds`? instead of `populate`?

two or more calls instead one?

**Comment by nodkz** [comment]
Yep, it does not use `populate`.
`For each property` is called `GraphQL N+1 query problem` and may be solved via https://github.com/graphql/dataloader
