### ISSUE TITLE
Demo Project w/ Circular Dependencies

### ISSUE THREAD

**Issue by matthewpick** [graphql-compose/graphql-compose-mongoose#175]
@nodkz Thanks for such an awesome library!
This library has helped a lot with with building out the MVP backend for my React web app.

This "Issue" is more to document the learning process and conventions so others can learn too.

While stumbling along learning Node.js, Mongoose, GraphQL, and graphql-compose-mongoose at the same time, I came across an interesting Node.js issue around circular dependencies.

Example code can be found here: https://github.com/matthewpick/graphql-compose-mongoose-backend

My GraphQL Model:
Backend consists of `User` and `Club` (among other models).
A `User` can belong to multiple Clubs, and a `Club` can have many Users.

While trying to `require()` and use dependencies from other modules, I had an issue where `UserTC` would be undefined when trying to set up the circular dependency within `ClubTC`. This is not a surprise with a Many-To-Many relationship!

I followed this [Stackoverflow post](https://stackoverflow.com/questions/10869276/how-to-deal-with-cyclic-dependencies-in-node-js) to get past this problem for now, although it definitely isn't as clean as I'd hoped.

Maybe you have a better way of handling circular dependencies in Node.js?
Thanks!

**Comment by nodkz** [comment]
You met with hoisting problem. Just wrap `type` in thunk:

```diff
UserTC.addFields({
  club: {
-    type: ClubTC,
+    type: () => ClubTC,
  }
});
```

**Comment by matthewpick** [comment]
Hmm that is similar to the problem I was having, but [this](https://github.com/matthewpick/graphql-compose-mongoose-backend/blob/1946409095695cd06aae1e5b795062fe1c0a6b88/src/resolvers/user.js#L3-L19) is how I was able to solve it.
