### ISSUE TITLE
beforeQuery for findById(s)

### ISSUE THREAD

**Issue by antoniopresto** [graphql-compose/graphql-compose-mongoose#177]
Thank you for this package and all your hard work.

I'm implementing a custom authentication plugin to use with this package - `wrapResolve` can be used to meet most of the resolvers created by this package and change the query filter to return only the documents owned by the current user - except in the resolvers that have no filter (findById and findByIds).

Do you have any suggestions on how to solve this without reimplementing these methods? would be very nice if there were `beforeQuery` in all resolvers.

**Comment by antoniopresto** [comment]
I opened this issue just because of [this comment ](https://github.com/graphql-compose/graphql-compose-mongoose/blob/72fb7543de9761a3abcccb646fcb1a6985815311/src/resolvers/updateMany.js#L102). I'm planning to accomplish it with mongoose hooks anyway. Thank you again.

**Comment by nodkz** [comment]
@antoniopresto will be great when you get a working solution to share your solution in this issue for further googlers ;)

Thanks!
