### ISSUE TITLE
Cast error when using _operators inside prepareArgs

### ISSUE THREAD

**Issue by corydeppen** [graphql-compose/graphql-compose-mongoose#180]
I'm running into an error after upgrading to `graphql-compose-mongoose@7.1.2`. It seems like any relation that used `_operators` in `prepareArgs` is failing with an error like `CastError: Cast to ObjectId failed for value "{ _bsontype: 'ObjectID'...` when using something like the following:

```js
prepareArgs: {
  filter: source => ({
    _operators: {
      user: { in: source._id },
    },
  }),
},
```

If I pin to `v7.1.1` I don't see the errors and the relations work as expected.

**Comment by nodkz** [comment]
@corydeppen please provide a broken test for this case. It tremendously helps me to resolve the problem much faster. Thanks!

**Comment by corydeppen** [comment]
Sorry, this was my error. I didn't need to use `_operators` because I just needed to filter by `_id` and not items in an array.
