### ISSUE TITLE
Cannot read property '_operators' of null

### ISSUE THREAD

**Issue by corydeppen** [graphql-compose/graphql-compose-mongoose#181]
I'm getting an error `Cannot read property '_operators' of null` when using an arg like the following:

```js
filter: { _operators: { publishedAt: { ne: null } } }
```

It appears this is caused when `filter[OPERATORS_FIELDNAME]` is evaluated after [`processFilterOperators` is called with null](https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/resolvers/helpers/filterOperators.js#L52) in this case. By checking `filter` before `_prepareAndOrFilter(filter)` and returning `null` if `filter` didn't exist I received the expected results without an error.

I was wondering if you thought this simple fix was valid or if you had other thoughts.

**Comment by nodkz** [comment]
Thanks for reporting and especially thanks for test case 👍
