### ISSUE TITLE
Error on type of Map

### ISSUE THREAD

**Issue by nino-moreton** [graphql-compose/graphql-compose-mongoose#186]
When I give a schema field of 
![image](https://user-images.githubusercontent.com/48229482/66019384-c2653f80-e515-11e9-8b20-401ec5652612.png)
it returns with error
```
graphql-compose-mongoose/node8/fieldsConverter.js:101
        throw new Error(`Field ${name} does not have schema property`);
        ^

Error: Field contact does not have schema property
```

I just copy and pasted the example here for Maps https://mongoosejs.com/docs/schematypes.html#maps

**Comment by smooJitter** [comment]
So does this package support map types?

**Comment by nodkz** [comment]
Nope, this package does not support Map types. With small fixes in codebase, it can support map types only as JSON type in GraphQL schema. GraphQL for the schema is very strict, it should know all available field names. But when names are unknown then only JSON type can be used.

If it is desired behavior for you let me know, I'll try to find some time the next week to fix it. Or even better if you send a pull request.

**Comment by ChrisLahaye** [comment]
@nodkz I am encountering the same problem, so I would appreciate the addition!
