### ISSUE TITLE
Ability to not add converted type to the global schemaComposer

### ISSUE THREAD

**Issue by chrispytoes** [graphql-compose/graphql-compose-mongoose#188]
Is it possible to use `composeWithMongoose` without adding the created object to the global `schemaComposer`? My application connects to several databases and I need a separate schema for each.

Am I missing something in the docs that lets you do this? Not having this is the only thing stopping me from using this library, which is a shame because it would be a big help for me.

**Comment by nodkz** [comment]
By default `composeWithMongoose` uses global `schemaComposer` for generated types. If you need to create different GraphQL schemas you need create own `schemaComposer`s and provide them to `customizationOptions`:

```js
import { SchemaComposer } from 'graphql-compose';

const schema1 = new SchemaComposer();
const schema2 = new SchemaComposer();

const UserTCForSchema1 = composeWithMongoose(User, { schemaComposer: schema1 });
const UserTCForSchema2 = composeWithMongoose(User, { schemaComposer: schema2 });
```

[Docs updated](https://github.com/graphql-compose/graphql-compose-mongoose/commit/f281d039c7dca692800c26fff9bdecbfe4ae333f)

**Comment by chrispytoes** [comment]
Thanks, that's what I was looking for.
