### ISSUE TITLE
Camelize mongoose schema fields

### ISSUE THREAD

**Issue by LucGranato** [graphql-compose/graphql-compose-mongoose#194]
Hi people!

I would like to know the most practice way to make all my GraphQL fields `camelCase` while my schema has `snake_case` fields name.

My schema normally uses `snake_case` on fields name.
```javascript
const schema = new mongoose.Schema({
  first_name: String,
  last_name: String,
  email_address: String
});
```

But I would like to have all my fields in `camelCase` on the GraphQL.
```graphql
firstName: String
lastName: String
emailAddress: String
```

I saw [here](https://github.com/graphql-compose/graphql-compose-mongoose/blob/ce596d42a5b50b7daf8223ee0010f333620e17fc/src/composeWithMongoose.js#L25) that is not possible yet to rename the fields name.

I will add this feature and make a pull request.
Any remarks I should worry about?

**Comment by nodkz** [comment]
You should worry about mapping fields in
- `args` when you receive args from a client you need provide renamed args to resolve methods (filtering, sorting should continue to work)
- `projection` when client request fields via graphql query you need to project (select) correct field names from the database.
- `resolve` when you return mongoose document in resolve method you need to map its fields to GraphQL field names.

It's a quite complicated task and of course, you need to write a lot of test cases for covering all current resolvers logic.

**Comment by LucGranato** [comment]
Thanks @nodkz !
The best approach that I found is to use the `alias` feature from mongoose.
Because mongoose will virtually apply getters and setters and handle query operations with the alias name.

I'm thinking to add an option here:
```typescript
export type ComposeWithMongooseOpts<TContext = any> = {
  schemaComposer?: SchemaComposer<TContext>;
  name?: string;
  description?: string;
  fields?: {
    only?: string[];
    remove?: string[];
    useAlias?: boolean;
  };
  inputType?: TypeConverterInputTypeOpts;
  resolvers?: false | TypeConverterResolversOpts;
};
```

The idea behind the option `useAlias` is to tell the library to use the alias name instead of the field name.

This will end up with something like this:
```javascript
const userSchema = new mongoose.Schema({
  email_address: {
    type: String,
    alias: 'emailAddress'
  }
});

const User = mongoose.model('user', userSchema);

const UserTC = composeWithMongoose(User, {
  fields: {
    useAlias: true
  }
});
```

Do you consider a decent approach?

**Comment by nodkz** [comment]
Wow! It will be amazing if mongoose takes care about field mapping. 👍

**Comment by nagug** [comment]
useAlias?: boolean;

is this functional? For reducing the size of the mongoldb, I am considering short field names. alias would be a great feature providing descriptive Field name for the API users

**Comment by RemyMachado** [comment]
I have done some research on the subject. If you are still hesitating on what case inside your mongo database to choose between `camelCase` & `snake_case`, I advise you to use `camelCase`. The data is intended to be used with JS and we know that converting back and forth the field names will only give problems.
