### ISSUE TITLE
Can't get value from nested relation

### ISSUE THREAD

**Issue by GimignanoF** [graphql-compose/graphql-compose-mongoose#196]
In my schema I have a model like this
```
document = {
   images: [ImageModel]
   metadata: {
      feedImage: ID
   }
}
```

```feedImage``` is an ID of a document in the ```images``` array. Now, what I want to achieve is to query the feedImage field to get some properties of the actual image in the image array, and not only the ID. I managed to create the relation, where I can get that ID and pass it to a resolver, however I'm struggling to get the actual value from the images array. This is how I defined the relation
```
DocumentTC.getFieldOTC("metadata")
  .addRelation("feedImage", {
    resolver: ImageResolver,
    prepareArgs: {
      _id: source => source.feedImage
    }
  });
```

And this is the resolver
```
const imageResolver = schemaComposer.createResolver({
  name: "findImages",
  type: ImageSchema,
  args: {
    _id: "ID!"
  },
  resolve: ({ source, args, context, info }) => {
    // Get image from top document
    return null;
  }
});
```

In the resolver I tried accessing the source, args, context and info params but none of them seems to let me access the top element, which in this case is the main document with the images array. So is it possible to do such relation, and how can I access that top document inside the resolver?

**Comment by GimignanoF** [comment]
I managed to somehow make it works by doing this
`const imageResolver = schemaComposer.createResolver({
  name: "findImages",
  type: ImageSchema,
  args: {
    _ids: "[ID!]"
  },
  resolve: async ({ source, args, context, info }) => {
    let images;
    let id = mongoose.Types.ObjectId(args._id);
    await DocumentModel.findOne(
      { "images._id": { $in: id } },
      { images: true, _id: false }
    )
      .lean()
      .exec()
      .then(res => {
        images = res.images;
      });
    return images.find(image => image._id.equals(args._id));
  }
});`

But I'm not sure if this is the correct approach. Any suggestions?

**Comment by nodkz** [comment]
As a `source` for resolver, you will get data from `metadata`. There is no other way to provide parent doc using above relations.

So I recommend you rewrite code in the following manner – on parent (document) level rewrite metadata field:

```js
DocumentTC.setField('metadata', {
  type: `type MyMetadata { feedImage: ImageType }`,
  projection: { images: 1 }, // for requesting this field From mongo, even this field not requested in GraphQL query 
  resolve:  async (source, args, context, info) => {
    const allDocumentImages = source.images;
    const metaFeedImage = source.metadata.feedImage;
    return allDocumentImages.find(image => image._id.equals(metaFeedImage._id));
  }
});
```

This solution is correct only if your `document` contains embedded data in `images` field.

**Comment by nodkz** [comment]
Resolver are good for simple cases. But when you need to do something complex, do not hesitate to rollback on the regular `resolve` method.

**Comment by GimignanoF** [comment]
Thank you for the answer, I'll refactor the code to use the setField function as certainly is cleaner and possibly less "mongo-intensive" :)

**Comment by GimignanoF** [comment]
I tried your example, however I can't figure out how to do the same for a more nested document. Say the document is something like this
```
document{
  images: [Images]
  metadata{
   properties{
    image: ID
   }
  }
}
```
How can I achieve the same result with a document like this? Since source only contains information about the direct parent, not the "parent of the parent" and so on :/

**Comment by nodkz** [comment]
Just return on top-level resolver deep nested result:

```js
DocumentTC.setField('metadata', {
  ...
  resolve: (source, args, context, info) => {
    return { properties: { image: 'example.png' } };
  }
});
```

**Comment by GimignanoF** [comment]
Thank you for your answer :) At the end I've just changed my model, so all images are in a separate collection, which allows me to handle relations way easier :) Anyway this can still comes in handy, thank you for the response :)
