### ISSUE TITLE
Advanced filtering for nested fields?

### ISSUE THREAD

**Issue by GimignanoF** [graphql-compose/graphql-compose-mongoose#197]
I have a query like this
```
document(_id: "some-id"){
 propertyA
 propertyB{
  status
 }
}
```
So ` propertyB ` is an object added via a virtual field to the schema, like so
```
DocumentSchema.addFields({
  propertyB : {
    type: [PropertyBSchema],
    args: {
      limit: {
        type: "Int",
        defaultValue: 3
      },
      skip: "Int",
      filter: toInputObjectType(PropertyBSchema)
    },
    resolve: async (source, args, context, info) => {
       //Do stuff
    }
  }
});
```

So far so good, i can query and filter the ` propertyB ` objects, but what if I need some advanced filtering? Let's say, I want all documents where ` propertyB.status ` is between some values. Right now it only allows me to check for a single value, so is there a way to tell graphql-compose to add such operators (like the ` operators ` field that adds to the main document filters) or should I wrote my own logic there?

**Comment by nodkz** [comment]
`graphql-compose` is a toolkit for writing any custom helpers (generators) which help to create you a graphql schema. `graphql-compose-mongoose` is a good example of such helper  – it takes mongoose models and according to their data generates for you Types and Resolvers. And of course such helpers and magic work in 95% for common cases. 

For rest 5% you need to write your custom helper functions. Fortunately, `graphql-compose` allows you to modify as you wish already generated types via your custom helper functions. 

So I strongly recommend you break the common borders and write your own logic where it needed. 👍

**Comment by nodkz** [comment]
As a good example of custom logic may be your previous issue https://github.com/graphql-compose/graphql-compose-mongoose/issues/196#issuecomment-559085433

**Comment by GimignanoF** [comment]
Got it :) Thank you for the answer ;)
