### ISSUE TITLE
Arguments for document fields

### ISSUE THREAD

**Issue by GimignanoF** [graphql-compose/graphql-compose-mongoose#198]
I have a document with this structure

```
fieldA: String
fieldB: [Array of fieldC]
```

Now, let's say I want to do a query like this

```
query{
   documents {
      fieldA
      fieldB(someProperty: someValue, limit: 2) {
             fieldCProperty
         }
     }
}
```

So get only a subset of the fieldB array, eventually filtered by some property.

I tried this
```
DocumentSchema.extendField("fieldB", {
  type: [FieldCSchema],
  args: {
    limit: {
      type: "Int",
      defaultValue: 2
    },
    skip: "Int"
  }
});
```

It successfully added those args to the field, however they are ignored when the query is launched :/ So is it possible to add such filters to the document fields?

**Comment by GimignanoF** [comment]
I have kinda solved this by doing this. Instead of calling extendField I add a relation on that field, which points to a resolver in where I apply the field arguments. Something like this
```
DocumentSchema.addRelation("fieldB", {
  resolver: fieldCResolver
});


const fieldCResolver = schemaComposer.createResolver({
  name: "fieldCResolver ",
  type: [fieldC],
  args: {
    limit: {
      type: "Int",
      defaultValue: 4
    },
    skip: "Int"
  },
  resolve: async ({ source, args, context, info }) => {
    return source.fieldB.slice(args.limit * args.skip, args.limit);
  }
});
```

This way the limit and skip arguments works, and of course with more logic other filters should too. But I don't know if is the right approach, since I'm adding a relation where there isn't one :/ So what could be a better (and right) approach to this?

**Comment by nodkz** [comment]
Every field with arguments just allows passing client data to the second argument in `resolve(source, args, context, info)` method. Then you need to read `args` in your `resolve` code and implement logic yourself.

When you find much duplicate code in your FiledConfigs, you may create Resolver. Resolver is the same what is FieldConfig in GraphQL – it keeps `type`, `args`, `resolve`, and other properties. One difference that Resolver created for use in multiple places. Eg you have `User.findById` resolver and want to reuse same logic for `Article.author`, `Comment.user` fields.

So firstly better to not use Resolvers. And when you find that the same code for some Entity used many times then make from them Resolver.

**Comment by GimignanoF** [comment]
Thank you for the response :) Yes I'm already "reusing" resolvers where I need (for instance where I have a document ID in the model to get all the model details)
