### ISSUE TITLE
Making fields mandatory while record create and optional while record update

### ISSUE THREAD

**Issue by ishwinder** [graphql-compose/graphql-compose-mongoose#206]
This is not really an issue but a query, if we have some SO tag, please point me to that and I can post it there.

Since the library is mostly generating the same input type for create and update mutations, is there a way/option to make some params mandatory while passing in create mutation and optional while passing in update mutation ?

**Comment by nodkz** [comment]
This library generates different input types for resolvers. So `createOne` and `updateOne` has different input types.

```js
UserTC.getResolver('createOne').getArg('record').makeFieldNonNull(['field1', 'field2']);
UserTC.getResolver('updateOne').getArg('record').makeFieldNullable(['field1', 'field2']);
```

**Comment by ishwinder** [comment]
> This library generates different input types for resolvers. So `createOne` and `updateOne` has different input types.
> 
> ```js
> UserTC.getResolver('createOne').getArg('record').makeFieldNonNull(['field1', 'field2']);
> UserTC.getResolver('updateOne').getArg('record').makeFieldNullable(['field1', 'field2']);
> ```

That worked well, thanks a lot for the amazing library !
