### ISSUE TITLE
sort by two indexes

### ISSUE THREAD

**Issue by ahelord** [graphql-compose/graphql-compose-mongoose#210]
how to sort by two indexes with grapqhl compose mongoose? for example
{"sort":["_ID_ASC","LABEL_ASC"]}

**Comment by Cobelt** [comment]
Hello, any news about this feature ? It would be very helpful, thanks :)

**Comment by aaronkchsu** [comment]
Seriously helpful haha! Has anyone had any hack solutions?

**Comment by ahelord** [comment]
Excellent work @nodkz
