### ISSUE TITLE
FindMany filter arg type MongoID need to be coverted to string type

### ISSUE THREAD

**Issue by zapkub** [graphql-compose/graphql-compose-mongoose#22]
I found that findMany resolver's filter arg that has MongoID type doesn't work with mongoID input.

This is what it should be?, I think it will be better if it can work without `toString()`.

## Example
```js

....
    addRelation({
      name: 'episodesRelation',
      args: {
        filter: source => ({
          seasonId: source._id.toString(),  // this one need to be converted to String
        }),
      },
      resolver: EpisodeTC.getResolver('findMany'),
      projection: { _id: 1 },
    })

.....
    addFields({
      episodesFields: {
        type: EpisodeTC.getTypePlural(),
        args: {
          offset: { type: 'Int', defaultValue: 0 },
          limit: { type: 'Int', defaultValue: 10 },
        },
        // this directly one doesn't
        resolve: (source, { offset, limit }, { Episode }) => 
          Episode.find({ seasonId: source._id })
          .skip(offset)
          .limit(limit),
      },
    })

.... 
  addRelation({
      name: 'episodesRelation',
      argsMapper: {
        filter: source => ({
          seasonId: source._id, // this deprecated one doesn't too 😆
        }),
      },
      resolver: EpisodeTC.getResolver('findByIds'),
      projection: { _id: 1 },
    })
```

**Comment by nodkz** [comment]
I didn't understand why mongoose does not accept `seasonId` as BSON.

But we can not convert all args `toString()` by default because may be passed complex object. 

Internally I'm using the same pattern `toString` in several places in my schema.

So for now, let keep it as is. Need to discover the source of the problem more deeply.

**Comment by zapkub** [comment]
Okay, I will take a look on `helpers/filter.js` for further more !

**Comment by nodkz** [comment]
Any help really appreciated!

`helpers/filter.js` is a right place for finding bug in graphql-compose-mongoose or mongoose itself.

**Comment by nodkz** [comment]
This problem [was fixed](https://github.com/graphql-compose/graphql-compose-mongoose/commit/15b6f46c9296122268bf39268e727eefe5a3f216) several months ago 
https://github.com/graphql-compose/graphql-compose-mongoose/blob/9a90b82fddb93704341b3900e07a3fd351a409d1/src/utils/toMongoDottedObject.js#L35

Via checking `ObjectId` type and not "dotting" it.
