### ISSUE TITLE
Feature Request: Aggregate lookups for nested relationships

### ISSUE THREAD

**Issue by koredefashokun** [graphql-compose/graphql-compose-mongoose#223]
Started using this project today, and it's been great. However, from the documentation, I noticed that nested relationships in the tables are handled with resolvers. In my experience, this might lead to some performance bottlenecks, as a result of the N+1 problem (see [this video](https://www.youtube.com/watch?v=uCbFMZYQbxE&t=420s)).

A better approach would be to handle this with MongoDB's native aggregate [`$lookup`](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/) feature (very similar to SQL joins). This would reduce the number of database calls required to fetch data for tables with these nested relationships.

As I'm new to this project, I apologise in advance if this goes against any of the goals of the project. I'm also not sure how this will fit in the existing API, but I'm happy to share further thoughts if requested.

**Comment by nodkz** [comment]
Try to find time in this or next month and add DataLoader to existing Resolvers.
