### ISSUE TITLE
Introspection has `_id` on embedded documents.

### ISSUE THREAD

**Issue by RobertLowe** [graphql-compose/graphql-compose-mongoose#239]
So there is an issue with `_id` being created on embedded documents / objects.

Consider the following document:

```
{
  _id: "foobar",
  emails: [{address: "foo@example.com}]
}
```

Will be introspected with: `_id`:

![Screen Shot 2020-08-01 at 11 58 54 PM](https://user-images.githubusercontent.com/601141/89115169-18b34f80-d453-11ea-9817-98b1d533a87d.png)

However after applying: `UsersComposition.getFieldOTC('emails').removeField('_id');`

![Screen Shot 2020-08-01 at 11 51 13 PM](https://user-images.githubusercontent.com/601141/89115181-341e5a80-d453-11ea-82ba-b796905dedf7.png)

It's gone. What's up here?

And example of the schema:

```
const UsersSchema = new Schema(
  {
    _id: { type: String }
    emails: [
      {
        address: {type: String, index: true},
        verified: Boolean
      },
    ],
  { strict: false, versionKey: false, autoIndex: false }
);
```

**Comment by RobertLowe** [comment]
I found the root cause for this:

https://github.com/Automattic/mongoose/blob/766e06e126459094bca1cf4659093af115ce6c95/lib/helpers/schema/handleIdOption.js#L5-L20

Mongoose by default will add `_id` to embedded documents. It needs to be disabled via:

```
    emails: [
      {
        _id: false,
        address: {type: String, index: true},
        verified: Boolean
      },
    ],
```

This can be closed, but may be worth documenting some how. Hopefully this issue posting will help someone some day.

**Comment by nodkz** [comment]
Thanks a lot for your investigation. Add a note to the readme.

**Comment by RobertLowe** [comment]
Awesome, thanks @nodkz !
