### ISSUE TITLE
Is there a better way to resolve custom input arguments?

### ISSUE THREAD

**Issue by RobertLowe** [graphql-compose/graphql-compose-mongoose#242]
I have this working:

```
StudentsComposition.schemaComposer.createInputTC({
  name: 'CountryLocationOperatorsFilterFindManyStudentsInput',
  description: 'country operators',
  fields: {
    in: {
      type: '[String]',
      name: 'in',
      description: 'Location'
    }
  }
})

StudentsComposition.schemaComposer.createInputTC({
  name: 'LocationOperatorsFilterFindManyStudentsInput',
  description: 'Location operators',
  fields: {
    country: {
      type: 'CountryLocationOperatorsFilterFindManyStudentsInput'
    }
  }
})

let studentMiddleware = next => rp => {
  rp.beforeQuery = (query, rp)=> {
    let countryIn = rp.args.filter?._operators?.location?.country?.in;
    if (countryIn.length >= 1) {
      query.in('location.country', countryIn)
    }
    return query;
  }

  return next(rp);
}

StudentsComposition.getResolver('findMany').getArgITC('filter').getFieldTC('_operators').setField('location', {type: 'LocationOperatorsFilterFindManyStudentsInput'});

StudentsComposition.setResolver('findMany', StudentsComposition.getResolver('findMany').wrapResolve(studentMiddleware))
StudentsComposition.setResolver('pagination', StudentsComposition.getResolver('pagination').wrapResolve(studentMiddleware))
```

So I'm adding `_operators.location.country.in` and then I have a middleware to handle the filter...

It feels weird to have to disconnect the resolution from the input argument but I can understand why, I'm just at a blank of what should be done as an alternative.

A second thing that feels weird is having to reset the resolvers `findMany` and `pagination`, for some reason I cant just apply it to `findMany`, I need to apply it to both even though pagination wraps `findMany`.

This all feels like one big hack, but I'm learning!

**Comment by RobertLowe** [comment]
To add to this, it appears that `filter`'s `_operators` aren't recursive, they don't transform for nested properties:

```
const UsersSchema = new Schema(
  {
    billingAddress: {
      country: {type: String, index: true}
   }
})
```

`country`/`billingAddress` won't appear under `_operators`, changing it to:

```
const UsersSchema = new Schema(
  {
    billingAddress: {
      type: Object,
      index: true,
      country: {type: String, index: true}
   }
})
```

`billingAddress` will appear but `country` will not be nested inside of it.

My conclusion is `filterOperators` only handles the first level of properties and does not behave recursively. :(

**Comment by nodkz** [comment]
Yep, it looks like `_operators` don't support nested fields. If you create a PR with a broken test in this folder  https://github.com/graphql-compose/graphql-compose-mongoose/tree/master/src/__tests__/github_issues I can find time to figure this out and fix it.

Your solution provided above about extending already generated resolvers with additional logic is correct. And yep it looks weird and complex. This is a result of the current design of the resolver generation. `graphql-compose-mongoose` just creates `findMany` resolver which contains return type, args, and resolve method. The creation of `pagination` resolver has used these particles which helps to create new graphql types for pagination. Under the hood just reused `resolve` method from `findMany`. So there is impossible to provide inheritance - when you change `findMany`, then automatically change `pagination`. Moreover, in some cases, inheritance can be undesirable behavior. 

So when you call `composeWithMongoose` only at this time are generated all types & resolvers - the building blocks which you can modify in a programmatic way. And now I see that [customization-options](https://github.com/graphql-compose/graphql-compose-mongoose#customization-options) can be extended with some additional properties which can improve the first generation phase. I open to any suggestions on how it can be improved.

PS. In my cases when such complex logic became too heavy I'm writing such resolvers by hands from scratch (frankly, by own functions which generate types & resolvers). So `graphql-compose-mongoose` solves 95% of common cases, but as always the rest 5% is most important ))) It's very difficult to provide generators which fit all cases. There are too many compromises.
