### ISSUE TITLE
Can you filter by dates or integegers using a range pagination?

### ISSUE THREAD

**Issue by aaronkchsu** [graphql-compose/graphql-compose-mongoose#251]
I noticed the filter parameter let's you filter out a lot of parmeters. And you can sort by ascending and descending date

is there a way to filter using the $gt parameter for dates or find items within a range?

**Comment by aaronkchsu** [comment]
Also do want to add this has been an amazing project!

**Comment by nodkz** [comment]
Yep just extend resolver via `addFilterArg()`. This methods return new resolve which can be used in your schema. Follow this quite old issue, but it still actual and should work - 
https://github.com/graphql-compose/graphql-compose/issues/22#issue-181347846
