### ISSUE TITLE
Refactor resolver creation

### ISSUE THREAD

**Issue by nodkz** [graphql-compose/graphql-compose-mongoose#263]
This discussion was started here: https://github.com/graphql-compose/graphql-compose/issues/281#issuecomment-688262405

I was working under a new major version of `graphql-compose-mongoose` in my free time. And there was added 8 new resolvers and two old resolvers were changed with breaking changes. So according to these changes, I feel that storing resolvers in ObjectTypeComposer has the following disadvantages:
- no static analysis for resolver names
- no static analysis for available args when you are crating relations
- quite awkward mechanics of creating new resolvers and wrapping them
- no `go-to` support in IDE via ctrl+click for opening resolver definition

There is a long way but something already has done:
- There were improved typescript definitions. Now generated Resolvers know `source: Model<IDoc>`
- Created a new method `composeMongoose` which does not generate resolvers. 
  - It adds `generateResolver` property to TypeComposer with resolver generators. And when you need a resolver you may generate it in such way `PostTC.generateResolver.findMany()` (before was `PostTC.getResolver('findMany')`).
  - Generating resolvers on demand allows you:
    - Modify TypeComposer in a programmatic way and only after that generate resolvers with customized fields
    - Safe memory and time on bootstrap server phase, because won't b generated unused resolvers
    - You may call resolver generators several times with different configurations.

And for now looks so:

```ts
import { schemaComposer, graphql } from 'graphql-compose';
import { composeMongoose } from 'graphql-compose-mongoose';
import mongoose, { Document } from 'mongoose';

const UserSchema = new mongoose.Schema({
  name: { type: String, required: true },
});

interface IUser extends Document {
  name: string;
}

const PostSchema = new mongoose.Schema({
  title: { type: String, required: true },
  authorId: { type: mongoose.Types.ObjectId },
  reviewerIds: { type: [mongoose.Types.ObjectId] },
});

interface IPost extends Document {
  title: string;
  authorId?: mongoose.Types.ObjectId;
  reviewerIds?: [mongoose.Types.ObjectId];
}

const UserModel = mongoose.model<IUser>('User', UserSchema);
const PostModel = mongoose.model<IPost>('Post', PostSchema);

const UserTC = composeMongoose(UserModel);
const PostTC = composeMongoose(PostModel);

PostTC.addRelation('author', {
  resolver: UserTC.generateResolver.dataLoaderLean(), // <------ added `generateResolver` with all resolvers
  prepareArgs: {
    _id: (s) => s.authorId,
  },
  projection: { authorId: true },
});

PostTC.addRelation('reviewers', {
  resolver: UserTC.generateResolver.dataLoaderManyLean(), // <------ added `generateResolver` with all resolvers
  prepareArgs: {
    _ids: (s) => s.reviewerIds,
  },
  projection: { reviewerIds: true },
});

schemaComposer.Query.addFields({
  posts: PostTC.generateResolver.findMany(), // <------ added `generateResolver` with all resolvers
});

const schema = schemaComposer.buildSchema();
```

**Comment by nodkz** [comment]
@toverux how do you think - `generateResolver` is a good name or not? 

```
PostTC.addRelation('reviewers', {
  resolver: UserTC.generateResolver.dataLoaderManyLean(), // <------ added `generateResolver` with all resolvers
  prepareArgs: {
    _ids: (s) => s.reviewerIds, // <-------  `s` infers its type `IPost` automatically
  },
  projection: { reviewerIds: true },
});
```
The whole example you may see above.

**Comment by toverux** [comment]
Awesome work! Increased type safety and performance will be much welcomed.

`generateResolver` as a property is strange because it looks like a method name, ie. it sound like it performs an action.

I'd rather call it something like `resolversFactory`, `resolversGenerator` or just `resolvers`.

But you may also want to give it a name that is specific to graphql-compose-mongoose, right? Like `mongooseResolvers` or something, unless other plugins could extend this object again in turn, but there's a risk of collision.

**Comment by nodkz** [comment]
@toverux `{ lean: boolean }` option very good suggestion – opened issue for this feature https://github.com/graphql-compose/graphql-compose-mongoose/issues/266

Yep, I also dislike `generateResolver` name. And I was right for asking your advise – `mongooseResolvers` is the best name! In our apps, we are using different data sources so visibility will be greatly improved for developers with `UserTC.mongooseResolvers.find()`, `UserTC.elasticResovers.find()`.

**Comment by nodkz** [comment]
You may try a new version [v9.0.0-alpha.6](https://github.com/graphql-compose/graphql-compose-mongoose/releases/tag/v9.0.0-alpha.6).
As a playground, you may use this test suite https://github.com/graphql-compose/graphql-compose-mongoose/blob/alpha/src/__tests__/github_issues/141-test.ts

I suppose that you'll very like `testFieldConfig` helper (execute integration graphql query without blowing the code). For `field` property you may pass any graphql field config object. With Resolvers it works a little better - it has simple auto-complete of args names and checks for required args:
https://github.com/graphql-compose/graphql-compose-mongoose/blob/a136386ec909449d0e4d089d968435438a6db4a4/src/__tests__/github_issues/141-test.ts#L163-L174

Please take a look. If you will have any ideas for issues - please let me know.

**Comment by nodkz** [comment]
You may try a new version [v9.0.0-alpha.6](https://github.com/graphql-compose/graphql-compose-mongoose/releases/tag/v9.0.0-alpha.6).
As a playground, you may use this test suite https://github.com/graphql-compose/graphql-compose-mongoose/blob/alpha/src/__tests__/github_issues/141-test.ts

I suppose that you'll very like `testFieldConfig` helper (execute integration graphql query without blowing the code). For `field` property you may pass any graphql field config object. With Resolvers it works a little better - it has simple auto-complete of args names and checks for required args:
https://github.com/graphql-compose/graphql-compose-mongoose/blob/a136386ec909449d0e4d089d968435438a6db4a4/src/__tests__/github_issues/141-test.ts#L163-L174

@toverux **Please take a look. If you will have any ideas for issues - please let me know.**

**Comment by nodkz** [comment]
@toverux can I ask you to review [release notes for v9.0.0](https://github.com/graphql-compose/graphql-compose-mongoose/blob/alpha/docs/releases/9.0.0.md)?

If you will have any questions, additions, or fixes – please write them here (or you may make fixes via PR for the `alpha` branch).
Thanks.
