### ISSUE TITLE
Question - Why nested fields return the entire subdocument in Projection

### ISSUE THREAD

**Issue by natac13** [graphql-compose/graphql-compose-mongoose#271]
I was trying to convert over to using this library, as the amount it handle is very impressive! However, I came across a pet-peeve of mine (which may not be a big deal). 
When querying for a subdocument or in an array of subdocuments I see that this library will project the entire subdocument and not just the required sub-field. 

For example
```js
export const AuthorSchema = new Schema(
  {
    name: String,
    birthday: Date,
    strings: [String]
  },
  { _id: false }
);

export const BookSchema = new Schema({
  title: String,
  pages: Number,
  authors: [AuthorSchema],
  primaryAuthor: AuthorSchema,
});
```

With graphql query 

```graphql
query {
  bookMany {
    title
    primaryAuthor {
      name
    }
  }
}
```
Should yield 
```
BookModel.find({}, { title: 1, 'primaryAuthor.name': 1 })
```

But instead this library yields
```
BookModel.find({}, { title: true, primayAuthor: true })
```

I am wondering if there is a reason I do not see why this was done? Or are you open to a PR to change this behaviour?

**Comment by nodkz** [comment]
@natac13 really I don't remember any special cases where subdocuments are required for retrieving in full projection. Maybe it just not fully implemented. 🤗

Anyway, on a PR it's a good feature improvement. 👍 
So if there was some special reason for that then it should be caught by tests. Feel free to open PR with broken tests, I'll help to resolve them 😉

PS. It would be great if you open PR on top of the `alpha` branch. This week I'll publish a new major 9.0.0 version. Right now I'm testing it internally on our private apps. Changes in [milestone](https://github.com/graphql-compose/graphql-compose-mongoose/milestone/1?closed=1), last published version in npm [v9.0.0-alpha.8](https://github.com/graphql-compose/graphql-compose-mongoose/releases)

**Comment by natac13** [comment]
Np Ill branch off the `alpha` branch to get some test started. Can I ask if you would prefer them to go into `src/__tests__/integration-test.ts` or `/src/__tests__/github_issues/`? Under a new file?

**Comment by nodkz** [comment]
`/src/__tests__/github_issues/271-test.ts` is the best choice
