### ISSUE TITLE
Filter Query Operators

### ISSUE THREAD

**Issue by jovermier** [graphql-compose/graphql-compose-mongoose#277]
There seems to be no clear way to add query operators such as mongo's $eq, $gt, $gte, $in, $lt, $lte, $ne, $nin.

Example syntax would be
`{ <field>: { EQ: <value> } }`
`{ <field>: { GT: <value> } }`

The ideal graphql query would be
`inventory(filter: { tags: { NIN: [ "appliances", "school" ] } })`

or an even more advanced query
```
query {
  inventory(
    filter: {
      AND: [
        { tags: { NIN: ["appliances", "school"] } }
        { price: { GT: 10 } }
        { canBeSold: { EQ: true } }
      ]
    }
  ) {
    id
  }
}
```

**Comment by nodkz** [comment]
Did you try `_operators` field?

<img width="1504" alt="Screen Shot 2020-09-24 at 20 34 20" src="https://user-images.githubusercontent.com/1946920/94159448-6376a400-fea5-11ea-8b8e-e67a7ab6463d.png">

**Comment by jovermier** [comment]
Indexing must be enabled for each of the properties in the schema that filtering is desired.
Example: `price: { type: Number, index: true }`

Thanks, this resolves the confusion.

**Comment by nodkz** [comment]
@jovermier  can I ask you to review [release notes for v9.0.0](https://github.com/graphql-compose/graphql-compose-mongoose/blob/alpha/docs/releases/9.0.0.md)?

It contains some improvements to operators where you may enable operators for unindexed fields.

If you will have any questions, additions, or fixes – please write them here (or you may make fixes via PR for the `alpha` branch).
Thanks.

**Comment by jovermier** [comment]
That documentation really clears things up. I really like the ability adjust configuration options to enable operators on unindexed fields and select granular operators. Also the regex and exists is a really nice touch. Nice work!
