### ISSUE TITLE
Property 'mongooseResolvers' does not exist on type 'ObjectTypeComposer<unknown, unknown>'.

### ISSUE THREAD

**Issue by gitpancake** [graphql-compose/graphql-compose-mongoose#279]
Hey,

This package seems fantastic so far, and my app is setup using a basic implementation (Creating & Reading). This works well, however I would like to configure custom `input` options on the resolvers. For example, when a static type is created, it only needs to know about the `name` of that static type.

So far, I've read this from the docs

![docs-screenshot](https://i.imgur.com/nAIdLOq.png)

However, when I try to implement this into my resolvers I get the error:

`Property 'mongooseResolvers' does not exist on type 'ObjectTypeComposer<unknown, unknown>'.`

Can anybody help with this?

Here is the implementation:

```
const customisationOptions = {
  name: "Time Interval Type",
  description:
    "A Time Interval Type is used to describe a time interval in the system.",
};

const TimeIntervalTypeComposer = composeWithMongoose(
  Model,
  customisationOptions
);

schemaComposer.Query.addFields({
  findTimeIntervalType: TimeIntervalTypeComposer.mongooseResolvers.findById(),
});

schemaComposer.Mutation.addFields({
  timeIntervalTypeCreateOne: TimeIntervalTypeComposer.getResolver("createOne"),
});
```

**Comment by gitpancake** [comment]
Actually, I just fixed this.

Previous version being used was `^8.0.4`. This was installed by default when I ran `npm install graphql-compose-mongoose`

I manually updated to `9.0.0`, reran `npm install` and it worked!

Just changed the implementation to:

```
import { schemaComposer } from "graphql-compose";
import { composeMongoose } from "graphql-compose-mongoose";

const customisationOptions = {
  name: "Time Interval Type",
  description:
    "A Time Interval Type is used to describe a time interval in the eNVM system.",
};

const TimeIntervalTypeComposer = composeMongoose(Model, customisationOptions);

schemaComposer.Query.addFields({
  findTimeIntervalType: TimeIntervalTypeComposer.mongooseResolvers.findById(),
});

schemaComposer.Mutation.addFields({
  timeIntervalTypeCreateOne: TimeIntervalTypeComposer.getResolver("createOne"),
});
```

**Comment by nodkz** [comment]
Yep, v9.0.0 was published just several hours ago. I'm glad that you resolved this issue.

BTW you need to change the mutation:
```diff
schemaComposer.Mutation.addFields({
-  timeIntervalTypeCreateOne: TimeIntervalTypeComposer.getResolver("createOne"),
+  timeIntervalCreateOne: TimeIntervalTypeComposer.mongooseResolvers.createOne(),
});
```

`getResolver("createOne")` - have a lot disadvantages which are described here https://github.com/graphql-compose/graphql-compose-mongoose/blob/alpha/docs/releases/9.0.0.md#a-new-way-for-resolver-creation-via-factory

**Comment by gitpancake** [comment]
@nodkz ah, okay, I didn't realise this. Thanks!

**Comment by ulziibadrakh-p** [comment]
Its happen to me. 
    "graphql-compose": "^7.24.4",
    "graphql-compose-mongoose": "^9.0.1",

**Comment by 4romgod** [comment]
I am using version 10, but i still get the same error
