### ISSUE TITLE
Calling `resolver.getArgs()` resets the `filter` arguments

### ISSUE THREAD

**Issue by Thammada** [graphql-compose/graphql-compose-mongoose#288]
When calling `.getArgs()` on a mongoose resolver, arguments added by `addFilterArg` will get reset.
I also observe that calling `.addFilterArg()` on a cloned resolver also affect the original resolver, but calling `.addArg()` doesn't

See the following snippet:

```js
const mongoose = require('mongoose');
const { composeMongoose } = require('graphql-compose-mongoose');

const Person = mongoose.model('Person', new mongoose.Schema({
  firstName: String,
  lastName: String
}))

const PersonTC = composeMongoose(Person)

const findManyResolver = PersonTC.mongooseResolvers.findMany()

const personsResolver = PersonTC.mongooseResolvers.findMany().clone().addFilterArg({
  name: 'fullName',
  type: 'String'
}).addArgs({
  username: 'String'
})

console.log('personsResolver username', personsResolver.hasArg('username')) // true -> OK, expected
console.log('personsResolver filter.fullName', personsResolver.getArgITC('filter').hasField('fullName')) // true -> OK, expected

console.log('findManyResolver username', findManyResolver.hasArg('username')) // false -> OK, expected
console.log('findManyResolver filter.fullName', findManyResolver.getArgITC('filter').hasField('fullName')) // false -> NOT EXPECTED, .addFilterArg not consistent with .addArg

PersonTC.mongooseResolvers.findMany().getArgs() // this line resets the `filter` arguments
// calling findManyResolver.getArgs() does not trigger the issue

console.log('personsResolver username', personsResolver.hasArg('username')) // true -> OK, expected
console.log('personsResolver filter.fullName', personsResolver.getArgITC('filter').hasField('fullName')) // false -> NOT EXPECTED, `filter.fullName` suddenly disappeared

console.log('findManyResolver username', findManyResolver.hasArg('username')) // false
console.log('findManyResolver filter.fullName', findManyResolver.getArgITC('filter').hasField('fullName')) // false

```

**Comment by nodkz** [comment]
@Thammada I need to clarify some new concept added to v9.0.0:
`PersonTC.mongooseResolvers.findMany()` – now creates resolver & subtypes every time when you call it. No need to call `clone()` method.

In your case, you creating several resolvers but under the hood, they are using the same input types with the same names.
So existed types may be overwritten. For avoiding this bad behavior you need to provide a custom suffix when you call `findMany()` fabric method.

Eg the following code will create two different resolvers with different subtype names which helps to avoid type name collisions:
```ts
const findManyResolver = PersonTC.mongooseResolvers.findMany();
const personsResolver = PersonTC.mongooseResolvers.findMany({ suffix: 'Extended'}).addFilterArg({ // <--- add any suffix
  name: 'fullName',
  type: 'String'
}).addArgs({
  username: 'String'
});
```

**Comment by toverux** [comment]
Hi @nodkz,

> In your case, you creating several resolvers but under the hood, they are using the same input types with the same names. So existed types may be overwritten.

I encountered the same issues and it was hard to troubleshoot.
I am migrating an app to v9 and somewhere I have this:

```
const findMany = tc.mongooseResolvers.findMany().addFilterArg(brandFilter);
const connection = tc.mongooseResolvers.connection();
const pagination = tc.mongooseResolvers.pagination();
```

Calling connection() or pagination() after the modded findMany() effectively makes the filter arg disappear.
I find this to be very surprising and unexpected.

To make it work, I have to append the addFilterArg call to pagination(), the last call that generates the filter input type shared by all these resolvers.

Shouldn't a new resolver reuse the existing subtypes when they already exist?
It's not perfect, in both cases there are side-effects, but it seems more logical.
Older versions were working like this.

**Comment by nodkz** [comment]
@toverux Good catch! I've just added customization param `findManyResolver` to `connection` & `pagination` resolvers.

A new version will be published in some minutes.
With your example above you will need to create resolvers in the following way:

```ts
const findMany = tc.mongooseResolvers.findMany().addFilterArg(brandFilter);
const connection = tc.mongooseResolvers.connection({ findManyResolver: findMany });
const pagination = tc.mongooseResolvers.pagination({ findManyResolver: findMany });
```

**Comment by nodkz** [comment]
Also for `filterHelperArgs()` I added reusing of existed type if it is already present in schema.

**Comment by toverux** [comment]
As always @nodkz, you're being just awesome. I will try it asap but I like this API, thank you very much!
