### ISSUE TITLE
Where __typename field comes from? [noob question]

### ISSUE THREAD

**Issue by ulziibadrakh-p** [graphql-compose/graphql-compose-mongoose#308]

**Comment by nodkz** [comment]
From graphql itself. This is in graphql specification.

**Comment by ulziibadrakh-p** [comment]
Thank you.  How  do I get this field? 
No such field in my query field options. Do I need additional configuration? 
![image](https://user-images.githubusercontent.com/169289/107740220-954db180-6d45-11eb-80b0-2b1cf4df0887.png)
