### ISSUE TITLE
payload.error field for custom mutation created via addResolver

### ISSUE THREAD

**Issue by exneval** [graphql-compose/graphql-compose-mongoose#310]
As we already know that v9.0.0 add error field as response in all schema mutation resolvers,
but is there a way to also add this field into custom mutation created via addResolver?

Please take a look into these @nodkz 
Thanks in advance

**Comment by nodkz** [comment]
Just call `addErrorCatcherField(resolver);` and it adds the error field and wraps the resolver.

https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/resolvers/createOne.ts#L100

If you will need something special, just dive into `addErrorCatcherField` code and write your own implementation.

**Comment by exneval** [comment]
@nodkz thanks for fast response

Actually I already try it, but not working, guess I implemented with a wrong way..
But now it's already working, thanks for clarifying that for me

for anyone who's wondering how it's done
```
const { addErrorCatcherField } = require('graphql-compose-mongoose/lib/resolvers/helpers/errorCatcher');

// any code

UserTC.addResolver({
  name: 'logout',
  kind: 'mutation',
  args: anyArgs,
  type: anyType,
  resolve: async ({ source, args, context, info}) => {
    // any code
  },
});

addErrorCatcherField(UserTC.getResolver('logout'));
```

**Comment by exneval** [comment]
@nodkz  Maybe allow `addErrorCatcherField` to import from graphql-compose-mongoose will be great

**Comment by nodkz** [comment]
Maybe. I do not want to expose a lot of functionality because in the future it may block me from some kind of changes. So for now, let's keep it as is.

If somebody else is using this feature please drop a comment or add a reaction (thumb up/down) to this comment. Tnx.
