### ISSUE TITLE
Custom filters breaks mongo queries with 9.0.1

### ISSUE THREAD

**Issue by fklingler** [graphql-compose/graphql-compose-mongoose#315]
Hello, I encountered a bug with the newer versions of graphql-compose-mongoose.

I have this custom filter added to my findMany resolver:

```
    .addFilterArg({
        name: 'from',
        type: GraphQLDate,
        description: 'Appointment date should be after the provided date.',
        query: (rawQuery: any, value: Date) => {
            rawQuery.date = {
                $gte: value,
                ...(rawQuery.date && typeof(rawQuery.date) != 'object'
                    ? { $eq: rawQuery.date }
                    : (rawQuery.date ?? {}))
            };
        }
    })
```

When using this filter, the mongo query should be like this (and was like this up to 9.0.0):

```
appointments.find({ date: { '$gte': new Date("Fri, 01 Jan 2021 23:00:00 GMT") }}, { limit: 100, projection: { _id: true, name: true }})
```

Now it is like this:

```
appointments.find({ from: new Date("Fri, 01 Jan 2021 23:00:00 GMT"), date: { '$gte': new Date("Fri, 01 Jan 2021 23:00:00 GMT") }}, { limit: 100, projection: { _id: true, name: true }})
```

Note the added `from` field in the find query, that makes it return no document.

This bug has been introduced in 9.0.1, the faulty commit is probably this one https://github.com/graphql-compose/graphql-compose-mongoose/commit/313ea1f04d7bf9ef1e93e05be4f7f02fd5efec08

**Comment by pescoboza** [comment]
I am having the same issue:

**Comment by pescoboza** [comment]
The problem seems to be around the filter helpers.

It looks like the params gql params are inserted themselves before the actual `rawQuery` applied by `addFilterArg`.

Fiddled around with the debugger and got this:

![image](https://user-images.githubusercontent.com/52549707/112783366-07cbd580-9004-11eb-941b-16a9bcb6f2ec.png)

**Comment by nodkz** [comment]
@pescoboza thanks for the investigation. It helps greatly to resolve this issue!

@fklingler your issue added as test-case https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/__tests__/github_issues/315-test.ts

A new package version will be published in minutes.
