### ISSUE TITLE
Extend `Pagination` (or any) return types?

### ISSUE THREAD

**Issue by andrewmartin** [graphql-compose/graphql-compose-mongoose#320]
Hi there,

Have been having a lot of luck with this package, and have used it wonderfully so far. I have hit a wall, however, and was wondering if someone could help me.

I've built out a custom "search" resolver that uses aggregations to combine a bunch of filters, and do some custom logic on the models directly. I followed some great posts in this repository.

```ts
TC.addResolver({
    name: 'searchProducts',
    type:  TC.getResolver('pagination'),
    kind: 'query',
    args: {
      name: 'String',
      limit: 'Int!',
      skip: 'Int!',
      categories: '[MongoID!]',
      ontologies: '[String!]',
    },
    resolve: async (rp: ResolveParams) =>  // ... returns ProductPagination (see below)
```

The type returned here is this:

```graphql
type ProductPagination {
  count: Int
  items: [Product!]
  pageInfo: PaginationInfo!
}
```

This works well! What I'd like to do, though, is extend this returned type to add another collection. The thing is, I'm using pagination and filtering on my aggregate search resolver, and I have the concept of "Tags." What I'd like to do is collect all of the tags found in that search and return the documents associated with them. Something simple like this:

```graphql
type ProductPagination {
  count: Int
  items: [Product!]
  tagItems: [Tag!] # my new custom return type here!
  pageInfo: PaginationInfo!
}
```

Should mention that `Tag`, in this example, is another `TC`. It's very vanilla and generic, so I'd imagine somehow there's a way to wire in `TagTC.getResolver('findMany')` as my return type here.

I think I'm fairly close, but I can't seem to find a way over the edge. Would appreciate any help!

**Comment by andrewmartin** [comment]
P.S. I can include more information in the `resolve` function, but I redacted most of it because it's largely irrelevant; I literally only want to change the returned type that comes back form this `addResolver` function.

Am I going down the wrong path? Should I be extending a resolver instead?

**Comment by yurtaev** [comment]
Do you want something like this?:

```js
const CountryTC = composeMongoose(Country)

const PagivationWithTags = CountryTC.mongooseResolvers.pagination().getOTC().clone('CountryWithTagsPagination')
PagivationWithTags.addFields({
    tags: '[String]',
})

CountryTC.extendField('_id', { type: 'String' })

schemaComposer.Query.addFields({
...requireMiddlewares([authMiddleware, permissionCountryMiddleware], {
    countryPagination: CountryTC.mongooseResolvers
    .pagination({ findManyOpts: FILTER_OPTIONS })

    countryPaginationCustom: CountryTC.mongooseResolvers
    .pagination({ findManyOpts: FILTER_OPTIONS })
    .setType(PagivationWithTags)
    .wrapResolve((next) => async (rp) => {
        const data = await next(rp)
        // ex.: add tags to response
        return { data, tags: data.items.map((i) => i.tag) }
    }),
}),
})
```

**Comment by andrewmartin** [comment]
Ah, thanks! This was all I needed, appreciate your help!

```ts
  const PaginationWithTags = TC.getResolver('pagination')
    .getOTC()
    .clone('ProductWithTagsPagination')

  PaginationWithTags.addFields({
    tags: '[String]',
  })

  TC.addResolver({
    name: 'searchProducts',
    type: PaginationWithTags,
    ....


```
