### ISSUE TITLE
Arrays and Objects Arrays are not working with mutations

### ISSUE THREAD

**Issue by theciphedwolf** [graphql-compose/graphql-compose-mongoose#329]
My Mongoose Schema 
`
trucks: [
    {
      TruckName: {
        type: mongoose.Schema.ObjectId,
        ref: "Truck",
      },
      TruckDescription: {
        type: String,
      },
    },
  ],
sponsor: [
    {
      name: {
        type: String,
      },
      url: {
        type: String,
      },
    },
  ],
location: {
    geo: {
      type: [Number], // [<longitude>, <latitude>]
      index: "2dsphere", // create the geospatial index
    },
  },
`

mutation with these properties is not working 

```const { trucks,location,sponsor } = obj;
    try {
      const res = await this.client.mutate({
        mutation: gql`
          mutation {
            eventCreateOne(
              record: {
                name: "${obj.name}"
                trucks:"${trucks}"
                sponsors:"${sponsors}" 
                location: {geo:${arr}} //For This line it gives me Error (GraphQLError: Syntax Error: Expected name, found Float )
                eventDate: "${obj.eventDate}"
                description: "${obj.description}"
                startTime: "${obj.startTime}"
                endTime: "${obj.endTime}"
                notes: "${obj.notes}"
              }
            ) {
              recordId
            }
          }
        `,
      });
      return res;
    } catch (ex) {
      console.log(ex);
    }```

I'm unable to understand issue here.

**Comment by yurtaev** [comment]
@theciphedwolf related #324

**Comment by theciphedwolf** [comment]
but i'm already using variables passed into function. Should i use graphql variable ?

**Comment by theciphedwolf** [comment]
> @theciphedwolf related #324

but i'm already using variables passed into function. Should i use graphql variable ?

**Comment by yurtaev** [comment]
Try. Also you can check a query that your client send to server.

**Comment by theciphedwolf** [comment]
> Try. Also you can check a query that your client send to server.

With apollo variable object everything works fine :)
Thanks for help !
