### ISSUE TITLE
upgrade issue from v7 to v9

### ISSUE THREAD

**Issue by rojectsky** [graphql-compose/graphql-compose-mongoose#345]
got loads of error when i tried to upgrade from 7.18.1 to 9.0.1:

ERROR in /Users/roject/workspace/sam/node_modules/graphql-compose/lib/index.d.ts
[tsl] ERROR in /Users/roject/workspace/sam/node_modules/graphql-compose/lib/index.d.ts(34,13)
      TS1005: ';' expected.

ERROR in /Users/roject/workspace/sam/node_modules/graphql-compose/lib/index.d.ts
[tsl] ERROR in /Users/roject/workspace/sam/node_modules/graphql-compose/lib/index.d.ts(34,741)
      TS1109: Expression expected.

ERROR in /Users/roject/workspace/sam/node_modules/graphql-compose/lib/index.d.ts
[tsl] ERROR in /Users/roject/workspace/sam/node_modules/graphql-compose/lib/index.d.ts(34,748)
      TS1005: ';' expected.

**Comment by yurtaev** [comment]
Are you using TypeScript < 4.0?

**Comment by rojectsky** [comment]
working good after the ts upgard
