### ISSUE TITLE
Current version incompatible with mongoose v6

### ISSUE THREAD

**Issue by JacquesLoubser** [graphql-compose/graphql-compose-mongoose#371]
Not an expert here.

When trying to use the latest graphql-compose-mongoose with latest mongoose (now v6 as of ) I get the following error:
`Right-hand side of 'instanceof' is not an object`

The issue comes from the `mongoose.Schema.Types.Embedded` object that seems to no longer exist in mongoose v6. https://github.com/graphql-compose/graphql-compose-mongoose/blob/c2449a99cf1a4547619d414d405aa99b98630a18/src/fieldsConverter.ts#L281

Can confirm the downgrading mongoose to v5 resolved the issue.

**Comment by nodkz** [comment]
@JacquesLoubser thanks for reporting
@canac thanks for investigation 

the new version will support both v5 & v6 🎉
