### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by smooJitter** [graphql-compose/graphql-compose-mongoose#39]
Whats the best way to define enums?

**Comment by nodkz** [comment]
Graphql-compose does not have a dedicated helper for complex Enums, but should. For now, I do not have a good idea how it should be implemented.

But as a workaround for simple enums (where key === value) you may use:
```js
UserTC.setFields({
  myEnum1: 'enum MyEnum1 { ID NAME AGE  }', // shortand field definition
  myEnum2: {
    type: 'enum MyEnum2 { ID NAME AGE  }',
    description: 'full field definition',
    resolve: (source, args, context, info) => {},
  },
});

// or you may use TypeMapper and reuse enum in different places
import { TypeMapper } from 'graphql-compose';
const typeMapper = new TypeMapper();
const MyEnum3 = typeMapper.createType('enum MyEnum2 { ID NAME AGE  }');
```

Complex Enum with specific values you may create in such way:
```js
import { graphql } from 'graphql-compose';

const MyEnum4 = new graphql.GraphQLEnumType({
  name: 'RGB',
  values: {
    RED: { value: 0 },
    GREEN: { value: 1 },
    BLUE: { value: 2 }
  }
});
```

I want to add `EnumComposer` module to `graphql-compose` but does not have any ETA. So use for now any of above methods.

**Comment by nodkz** [comment]
If your question was about Mongoose enums, so it can be defined in such way:
```js
export const ArticleSchema = new Schema(
  {
    ln: {
      type: String,
      description: 'Language names (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)',
      enum: ['en', 'fr', 'cn', 'kk'],
    },
  }
);
```

**Comment by Morphexe** [comment]
How can you then use the mongoose enums as arg in a resolver? A enum defined in  schema just like you did, in this case ArticleLangEnum?

**Comment by ziedHamdi** [comment]
graphQl error :  Expected type EnumEntityGroupEntityType, found "service"; Did you mean the enum value service?

		const ADD_SHOP = gql`
									mutation entityGroupCreate($name: String!,$web: String!,$fb: String!, $city: String!) {
    								entityGroupCreate(record:{name:$name, entityType: "service", web:$web, fb:$fb, city:$city}){recordId, record{_id, name, entityType, web, fb, city}}
  								}`
how do you pass that?

**Comment by ziedHamdi** [comment]
https://facebook.github.io/graphql/October2016/#sec-Enum-Value

**Comment by nodkz** [comment]
For enum creation, you may use `EnumTypeComposer`. It was added to `graphql-compose` at the beginning of 2018.
https://graphql-compose.github.io/docs/en/api-EnumTypeComposer.html

How it works you may see in tests
https://github.com/graphql-compose/graphql-compose/blob/master/src/__tests__/EnumTypeComposer-test.js
