### ISSUE TITLE
Removing mongoId field in a query fails

### ISSUE THREAD

**Issue by Anthonyzou** [graphql-compose/graphql-compose-mongoose#65]
HI,

Basically I have a schema with a mongoID in a field, and I would like to set it to null.
But everytime I run the query with the variables
```
{
  "input": {
    "_id": "59a59d8f9ae4fd3eb6e99b3a",
    "parentId": null
  }
}
```

The mongoId validator will give the error:
`"message": "FolderModel validation failed: parentId: Cast to ObjectID failed for value \"null\" at path \"parentId\"",`

**Comment by yoadsn** [comment]
@Anthonyzou What version of GQL-Compose-Mongoose are you using?
Which resolver did you call?
I tried to repro on the latest version without success.
Please paste a sample code of the resolver / model you use so we can look at this deeper.
