### ISSUE TITLE
Mongoose and Discriminators

### ISSUE THREAD

**Issue by MDrooker** [graphql-compose/graphql-compose-mongoose#78]
I have a schema that uses mongoose discriminators for a few objects.  One example is -
```js
let baseFollowSchema = mongoose.Schema({
    followuuid: { type: String, default: uuidv4() },
    createdDate: { type: Date, default: Date.now },
    effectiveStartDate: { type: Date, default: Date.now },
    effectiveEndDate: { type: Date, default: new Date(+new Date() + 30 * 24 * 60 * 60 * 1000) }, // 30 days
    metadata: [metaDataItemSchema],
    reviewData: [reviewDataItemSchema],
    isActive: { type: Boolean, default: true },
    isDeleted: { type: Boolean, default: false }
}, { discriminatorKey: 'followType' })
let Follow = mongoose.model('baseFollowSchema', baseFollowSchema, 'follow');


let KnowledgeGraphFollow = Follow.discriminator('followKGEntity',
    new mongoose.Schema({
        name: { type: String },
        followedKGIDs: [{
            kgid: { type: String },
            entityType: { type: String },
            name: { type: String },
            metadata: [metaDataItemSchema]
        }]
    })
);
```
[.... Other models excluded for simplicity] 

Is there a good example/test that can point me to how to implement the use of discriminators?
Thanks-
MJD

**Comment by asabhaney** [comment]
+1

**Comment by MDrooker** [comment]
Any thoughts/links to help the request above?

**Comment by nodkz** [comment]
Check this test-case 
https://github.com/graphql-compose/graphql-compose-mongoose/blob/ced77303174664454adda7b3b67d0010ebb25b50/src/__tests__/github-issues-test.js#L7-L20

Use "discriminated" model as a usual model on which can be called `composeWithMongoose` method for obtaining new GraphQL type.

If you want to remove `discriminatorKey` field (in my test case `kind` fieldname):
```js
// completely remove `kind` field from all generated types
ClickedLinkEventTC = composeWithMongoose(ClickedLinkEvent, { fields: { remove: ['kind'] } });

// Or remove it just from OutputType
ClickedLinkEventTC.removeField('kind');

// Or remove it just from InputType
ClickedLinkEventTC.getInputTypeComposer().removeField('kind');
```

**Comment by MDrooker** [comment]
Great-
How would a Resolver look since the return type can now be two different 'typeConverted' schemas.  And I didnt see where the we can have that be multiple.

**Comment by nodkz** [comment]
@MDrooker It very interesting to me how do you get a list of `Event`s and then convert some of them to extended `ClickedLinkEvent` with regular mongoose code? How I know mongoose cannot do this, or i'm wrong?

**Comment by MDrooker** [comment]
Mongoose converts to the proper model based on the Discriminator Key...
So this example will return true based on the StoryFollow being a returned record via the key

  async getAllFollows() {
    let follows = await Follow.find({ isActive: true }).exec();
    follows.map(follow => {
      let amIStoryFollow = follow instanceof StoryFollow
      console.log(`${follow.followType}- ${amIStoryFollow}`)  // should be true when type='followStory'
    })
  }

**Comment by MDrooker** [comment]
@nodkz Are you seeing that behavior also?

**Comment by nodkz** [comment]
@MDrooker all that you need you may find in this improved test case:
https://github.com/graphql-compose/graphql-compose-mongoose/blob/d2a2a18b31a0eb2d2182407b0a0384c4162e1244/src/__tests__/github-issues-test.js#L45-L97

**Comment by sergio91pt** [comment]
@nodkz What if its in a sub-document, as an array?
eg.`const sessionSchema = new mongoose.Schema({ 'generated': { 'events': [eventSchema]  } })`

**Comment by mernxl** [comment]
hello, I have gone through the comments, but really i wanted more flexibility, so i have gone ahead to create a small library that uses `graphql-compose-mongoose` under the hud. It creates a typeComposer, and an interface for the baseModel, then the baseTypeComposer exposes a `discriminator` function that returns a typeComposer that implements the baseType Interface.

It exposes a single function, `composeWithMongooseDiscriminator` that returns a custom `DiscriminatorTypeComposer` that has the `discriminator` method to create `ChildDiscriminatorTypeComposer`. The child is a normal TypeComposer with the baseInterface set as interface.

you can check out here, created a playground so you can test the library. 
[Graphql Playground With Functioning Schema and DB](https://graphql.finxel.com/playground)

![graphql-compose-mongoose-discriminators](https://user-images.githubusercontent.com/16241595/42135261-7721ea3e-7d40-11e8-88f6-c1a9c1718117.png)

There is a demo schema and a working database, you have all the compose-mongoose resolvers to play with. 

@nodkz is it possible you integrate this with `graphql-compose-mongoose` or should i create a `graphql-compose-mongoose-discriminators` repo? Really love to hear from you with regards to this, haven't published yet.

**Comment by nodkz** [comment]
@mernxl did amazing work. 
With `graphql-compose-mongoose@4.4.0` work with discriminators became work much easier
https://github.com/graphql-compose/graphql-compose-mongoose/releases/tag/v4.4.0
