### ISSUE TITLE
How to verify the fields?

### ISSUE THREAD

**Issue by nymlc** [graphql-compose/graphql-compose-mongoose#92]
I have a `User` model with `age` field and I want to verify the field is number
I can think of, just check resolveParams in wrapResolve

thanks

**Comment by nodkz** [comment]
By default graphql checks that field has `number` type. But if you want to add some additional checks you may do it via `wrapResolve`.

How I understood you want to do it with `mutation`, so it can be done in such way:
https://github.com/graphql-compose/graphql-compose-mongoose/blob/dad89088fa9e3428110426a194cd8479de0c3b42/src/__tests__/github-issues-test.js#L109-L113
Click on the filename for the detailed test case.

**Comment by nymlc** [comment]
@nodkz thank u for the test
